-- Vue d'ensemble CAF (mobile) — source : LES 20 GROS MONTANT A PROVISIONN -CAF.txt

WITH ENCOURS AS (
    SELECT
        e.ACCOUNT_NUMBER,
        e.BRANCH_CODE,
        SUM(e.AMOUNT_DUE - e.AMOUNT_SETTLED) AS TOTAL,
        SUM(CASE WHEN e.SCHEDULE_DUE_DATE >= SYSDATE THEN e.AMOUNT_DUE - e.AMOUNT_SETTLED ELSE 0 END) AS SAIN,
        SUM(CASE WHEN e.SCHEDULE_DUE_DATE < SYSDATE THEN e.AMOUNT_DUE - e.AMOUNT_SETTLED ELSE 0 END) AS IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES e
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER c ON c.ACCOUNT_NUMBER = e.ACCOUNT_NUMBER
    WHERE e.COMPONENT_NAME = 'PRINCIPAL'
      AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY e.ACCOUNT_NUMBER, e.BRANCH_CODE
),
PROVISIONS_AGG AS (
    SELECT
        C.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        C.ACCOUNT_NUMBER AS NO_PRET,
        c.PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        (SELECT MAX(u.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV u WHERE FIELD_NAME = 'GESTION_PRET' AND u.LOV = c.FIELD_CHAR_2) AS CHARGE_AFFAIRE,
        SUM(
            NVL(E.TOTAL, 0) * CASE
                WHEN C.USER_DEFINED_STATUS = 'DCL2' THEN 0.4
                WHEN C.USER_DEFINED_STATUS = 'DCL3' THEN 0.8
                WHEN C.USER_DEFINED_STATUS = 'DCL4' THEN 1
                ELSE 0
            END
        ) AS PROVISION_TOTAL,
        C.USER_DEFINED_STATUS
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER C
    JOIN ENCOURS E ON E.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.STTM_BRANCH BR ON BR.BRANCH_CODE = C.BRANCH_CODE
    WHERE C.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY
        BR.BRANCH_NAME,
        C.FIELD_CHAR_2,
        BR.BRANCH_CODE,
        C.ACCOUNT_NUMBER,
        c.PRIMARY_APPLICANT_NAME,
        C.USER_DEFINED_STATUS
)
SELECT *
FROM (
    SELECT
        PD.*,
        ROW_NUMBER() OVER (
            PARTITION BY CHARGE_AFFAIRE
            ORDER BY PROVISION_TOTAL DESC
        ) AS RN
    FROM PROVISIONS_AGG PD
)
WHERE RN <= 20
  AND PROVISION_TOTAL <> '0'
ORDER BY
    CHARGE_AFFAIRE,
    PROVISION_TOTAL DESC
