-- Vue d'ensemble CAF (mobile) — source : LES 20 GROS ENCOURS PAR 180 V2.txt

WITH NOMBRE_DOSSIER AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    GROUP BY p.FIELD_CHAR_2
),
ENCOURS_CAF AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.BRANCH_CODE,
        SUM(CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
        SUM(CASE WHEN CLS.SCHEDULE_DUE_DATE >= SYSDATE THEN CLS.AMOUNT_DUE ELSE 0 END) AS ENCOURS_SAIN,
        SUM(CASE WHEN CLS.SCHEDULE_DUE_DATE < SYSDATE THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED ELSE 0 END) AS ENCOURS_IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
    JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
    WHERE CLS.COMPONENT_NAME IN ('PRINCIPAL')
      AND p.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY p.FIELD_CHAR_2, p.BRANCH_CODE
),
ENCOURS_CODE_CAF AS (
    SELECT
        EC.CODE_GESTION_PRET,
        EC.BRANCH_CODE,
        EC.ENCOURS_TOTAL,
        EC.ENCOURS_SAIN,
        EC.ENCOURS_IMPAYE,
        NVL(ND.NOMBRE_DOSSIER, 0) AS NOMBRE_DOSSIER,
        TRUNC((EC.ENCOURS_IMPAYE / NULLIF(EC.ENCOURS_TOTAL, 0)) * 100, 2) AS RATIO_ENCOURS_IMPAYE,
        TRUNC((NVL(ND.NOMBRE_DOSSIER, 0) / NULLIF(SUM(ND.NOMBRE_DOSSIER) OVER (), 0)) * 100, 2) AS RATIO_NOMBRE_IMPAYE
    FROM ENCOURS_CAF EC
    LEFT JOIN NOMBRE_DOSSIER ND ON ND.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
    WHERE EC.ENCOURS_TOTAL <> 0
),
ECHEANCE_IMPY AS (
    SELECT
        CLS.ACCOUNT_NUMBER,
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.BRANCH_CODE,
        BR.BRANCH_NAME,
        p.PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        p.USER_DEFINED_STATUS AS STATUT_DECLASSEMENT,
        TRUNC(
            NVL(
                (
                    (SYSDATE - 1)
                    - TO_DATE(
                        (
                            SELECT MIN(Z.SCHEDULE_DUE_DATE)
                            FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES Z
                            WHERE Z.ACCOUNT_NUMBER = p.ACCOUNT_NUMBER
                              AND Z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
                              AND Z.SCHEDULE_DUE_DATE <= SYSDATE
                              AND ((Z.AMOUNT_DUE - Z.AMOUNT_SETTLED) > 0)
                              AND p.ACCOUNT_STATUS NOT IN ('L', 'V')
                        )
                    )
                ),
                0
            )
        ) AS NBRE_JOUR_RETARD,
        (SELECT MAX(u.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV u WHERE FIELD_NAME = 'GESTION_PRET' AND u.LOV = p.FIELD_CHAR_2) AS CHARGE_AFFAIRE,
        CLS.AMOUNT_DUE,
        CLS.AMOUNT_SETTLED,
        CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED AS PAR_CAPITAL_IMPY_ECH,
        CLS.SCHEDULE_DUE_DATE,
        SYSDATE - TO_DATE(CLS.SCHEDULE_DUE_DATE) AS NB_JOUR_IMPY
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.STTM_BRANCH BR ON BR.BRANCH_CODE = p.BRANCH_CODE
    WHERE CLS.COMPONENT_NAME IN ('PRINCIPAL')
      AND CLS.SCH_STATUS = 'IMPY'
),
FINAL_CLTB_ACCOUNT_SCHEDULES AS (
    SELECT
        ACCOUNT_NUMBER,
        COMPONENT_NAME,
        CASE
            WHEN COMPONENT_NAME IN ('ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT') THEN SCHEDULE_ST_DATE
            ELSE SCHEDULE_DUE_DATE
        END AS SCHEDULE_DUE_DATE,
        SCH_STATUS,
        AMOUNT_DUE,
        AMOUNT_SETTLED
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
),
EXIGIBLE AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS EXIGIBLE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN FINAL_CLTB_ACCOUNT_SCHEDULES z ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT')
      AND z.SCHEDULE_DUE_DATE <= SYSDATE
    GROUP BY c.ACCOUNT_NUMBER
),
PAR_DETAIL AS (
    SELECT
        CODE_GESTION_PRET,
        ACCOUNT_NUMBER AS NO_DOSSIER,
        EY.NOM_CLIENT,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 180 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS ENCOURS_PAR_180,
        ex.EXIGIBLE,
        EY.NBRE_JOUR_RETARD,
        EY.STATUT_DECLASSEMENT
    FROM ECHEANCE_IMPY EY
    LEFT JOIN EXIGIBLE ex ON ex.NO_PRET = EY.ACCOUNT_NUMBER
    GROUP BY
        ACCOUNT_NUMBER,
        CODE_GESTION_PRET,
        EY.NOM_CLIENT,
        EY.STATUT_DECLASSEMENT,
        EY.NBRE_JOUR_RETARD,
        ex.EXIGIBLE
)
SELECT *
FROM (
    SELECT
        PD.*,
        ROW_NUMBER() OVER (
            PARTITION BY CODE_GESTION_PRET
            ORDER BY ENCOURS_PAR_180 DESC
        ) AS RN
    FROM PAR_DETAIL PD
)
WHERE RN <= 20
  AND ENCOURS_PAR_180 <> '0'
ORDER BY
    CODE_GESTION_PRET,
    ENCOURS_PAR_180 DESC
