-- Top 20 gros encours PAR 180 (DUREE_IMPAYE > 180)
-- Alimente : Détail — PAR 180 (client, n° dossier, encours, exigible, jours)

WITH DUREE_IMPAYE_A_DATE AS (
    SELECT
        p.ACCOUNT_NUMBER,
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.USER_DEFINED_STATUS AS STATUT_DECLASSEMENT,
        NVL(
            TRUNC(SYSDATE) -
            (
                SELECT MIN(TRUNC(z.SCHEDULE_DUE_DATE))
                FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
                WHERE z.ACCOUNT_NUMBER = p.ACCOUNT_NUMBER
                  AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
                  AND z.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
                  AND (z.AMOUNT_DUE - z.AMOUNT_SETTLED) > 0
            ),
            0
        ) AS DUREE_IMPAYE_A_DATE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
),
ENCOURS AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        c.PRIMARY_APPLICANT_NAME,
        SUM(z.AMOUNT_DUE - z.AMOUNT_SETTLED) AS ENCOURS_TOTAL
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME = 'PRINCIPAL'
    GROUP BY
        c.ACCOUNT_NUMBER,
        c.PRIMARY_APPLICANT_NAME
),
EXIGIBLE AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS EXIGIBLE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME IN (
          'PRINCIPAL', 'MAIN_INT',
          'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT'
      )
      AND CASE
            WHEN z.COMPONENT_NAME IN ('ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT')
            THEN z.SCHEDULE_ST_DATE
            ELSE z.SCHEDULE_DUE_DATE
          END <= TRUNC(SYSDATE)
    GROUP BY c.ACCOUNT_NUMBER
),
ENCOURS_RISQUE AS (
    SELECT
        d.CODE_GESTION_PRET,
        e.NO_PRET,
        e.PRIMARY_APPLICANT_NAME,
        e.ENCOURS_TOTAL,
        d.DUREE_IMPAYE_A_DATE,
        d.STATUT_DECLASSEMENT,
        NVL(x.EXIGIBLE, 0) AS EXIGIBLE,
        CASE
            WHEN d.DUREE_IMPAYE_A_DATE > 0 THEN NVL(e.ENCOURS_TOTAL, 0)
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM ENCOURS e
    LEFT JOIN DUREE_IMPAYE_A_DATE d
        ON e.NO_PRET = d.ACCOUNT_NUMBER
    LEFT JOIN EXIGIBLE x
        ON x.NO_PRET = e.NO_PRET
),
PAR_DETAIL AS (
    SELECT
        CODE_GESTION_PRET,
        NO_PRET AS NO_DOSSIER,
        PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        ENCOURS_RISQUE AS ENCOURS_PAR_180,
        EXIGIBLE,
        DUREE_IMPAYE_A_DATE AS NBRE_JOUR_RETARD,
        STATUT_DECLASSEMENT
    FROM ENCOURS_RISQUE
    WHERE DUREE_IMPAYE_A_DATE > 180
      AND ENCOURS_RISQUE <> 0
)
SELECT *
FROM (
    SELECT
        PD.*,
        ROW_NUMBER() OVER (
            PARTITION BY CODE_GESTION_PRET
            ORDER BY ENCOURS_PAR_180 DESC
        ) AS RN
    FROM PAR_DETAIL PD
)
WHERE RN <= 20
ORDER BY
    CODE_GESTION_PRET,
    ENCOURS_PAR_180 DESC
