-- Vue d'ensemble CAF — portefeuille + détail PAR par CODE_GESTION_PRET
-- Alimente : Encours total, PAR 0/30/90/180/360, PAR Global

WITH NOMBRE_DOSSIER AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY p.FIELD_CHAR_2
),
NOMBRE_DOSSIER_IMP AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER_IMP
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND p.USER_DEFINED_STATUS NOT IN ('NORM', 'IMMO', 'DCL1')
    GROUP BY p.FIELD_CHAR_2
),
ENCOURS_RISQUE AS (
    SELECT
        ACCOUNT_NUMBER,
        CODE_GESTION_PRET,
        BRANCH_CODE,
        ENCOURS_TOTAL,
        ENCOURS_SAIN,
        ENCOURS_IMPAYE,
        DUREE_IMPAYE_A_DATE,
        CASE
            WHEN DUREE_IMPAYE_A_DATE > 0 THEN ENCOURS_TOTAL
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM (
        SELECT
            p.ACCOUNT_NUMBER,
            p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
            p.BRANCH_CODE,
            SUM(CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_SAIN,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_IMPAYE,
            NVL(
                TRUNC(SYSDATE)
                - MIN(
                    CASE
                        WHEN CLS.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
                         AND (CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) > 0
                        THEN CLS.SCHEDULE_DUE_DATE
                    END
                ),
                0
            ) AS DUREE_IMPAYE_A_DATE
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
        JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p
            ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
        WHERE CLS.COMPONENT_NAME = 'PRINCIPAL'
          AND p.ACCOUNT_STATUS NOT IN ('L', 'V')
        GROUP BY
            p.FIELD_CHAR_2,
            p.BRANCH_CODE,
            p.ACCOUNT_NUMBER
    )
),
PAR_DETAIL_CAF AS (
    SELECT
        EC.CODE_GESTION_PRET,
        SUM(EC.ENCOURS_TOTAL) AS ENCOURS_TOTAL,
        SUM(EC.ENCOURS_SAIN) AS ENCOURS_SAIN,
        SUM(EC.ENCOURS_IMPAYE) AS ENCOURS_IMPAYE,
        SUM(EC.ENCOURS_RISQUE) AS ENCOURS_RISQUE,
        MAX(NVL(ND.NOMBRE_DOSSIER, 0)) AS NOMBRE_DOSSIER,
        MAX(NVL(NDI.NOMBRE_DOSSIER_IMP, 0)) AS NOMBRE_DOSSIER_IMP,
        TRUNC(
            (SUM(EC.ENCOURS_IMPAYE) / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)) * 100,
            2
        ) AS RATIO_ENCOURS_IMPAYE,
        TRUNC(
            (
                MAX(NVL(NDI.NOMBRE_DOSSIER_IMP, 0))
                / NULLIF(MAX(NVL(ND.NOMBRE_DOSSIER, 0)), 0)
            ) * 100,
            2
        ) AS RATIO_NOMBRE_IMPAYE,
        -- PAR cumulatifs (> seuil)
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 0 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_0,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 30 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_30,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 90 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_90,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 180 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_180,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 360 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_360,
        -- Montants encours risque cumulatifs
        SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 0 THEN EC.ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_PAR_0,
        SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 30 THEN EC.ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_PAR_30,
        SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 90 THEN EC.ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_PAR_90,
        SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 180 THEN EC.ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_PAR_180,
        SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 360 THEN EC.ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_PAR_360,
        TRUNC(
            (SUM(EC.ENCOURS_RISQUE) / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)) * 100,
            2
        ) AS PAR_GLOBAL
    FROM ENCOURS_RISQUE EC
    LEFT JOIN NOMBRE_DOSSIER ND
        ON ND.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
    LEFT JOIN NOMBRE_DOSSIER_IMP NDI
        ON NDI.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
    GROUP BY EC.CODE_GESTION_PRET
),
GESTION_PRET AS (
    SELECT LOV, LOV_DESC
    FROM CFSFCUBS145.UDTM_LOV
    WHERE FIELD_NAME = 'GESTION_PRET'
)
SELECT
    T.CODE_GESTION_PRET,
    gp.LOV_DESC AS CHARGE_AFFAIRE,
    T.ENCOURS_TOTAL,
    T.ENCOURS_SAIN,
    T.ENCOURS_IMPAYE,
    T.ENCOURS_RISQUE,
    T.NOMBRE_DOSSIER,
    T.NOMBRE_DOSSIER_IMP,
    T.RATIO_ENCOURS_IMPAYE,
    T.RATIO_NOMBRE_IMPAYE,
    T.ENCOURS_PAR_0,
    T.PAR_0,
    T.ENCOURS_PAR_30,
    T.PAR_30,
    T.ENCOURS_PAR_90,
    T.PAR_90,
    T.ENCOURS_PAR_180,
    T.PAR_180,
    T.ENCOURS_PAR_360,
    T.PAR_360,
    T.PAR_GLOBAL
FROM PAR_DETAIL_CAF T
LEFT JOIN GESTION_PRET gp
    ON gp.LOV = T.CODE_GESTION_PRET
