-- Encours global client / prêt (Vue 360)
-- = capital restant (PRINCIPAL échéancier)
-- + intérêts & pénalités auto-settle (CHARGE_PRET)
-- + charges compte ACS / FOUV / COFC / FTEC (CHARGE)

WITH CHARGE AS (
    SELECT
        ACCOUNT_NO,
        ACCOUNT_BR,
        (SUM(AMOUNT_DUE) - SUM(AMOUNT_PAID)) AS CHARGE_DUE
    FROM CFSFCUBS145.CSTB_AUTO_SETTLE_BLOCK b
    WHERE STATUS <> 'P'
      AND COMPONENT = 'CHARGE'
      AND PRODUCT IN ('ASCP', 'ASSA', 'FOUV', 'COFC', 'FTEC')
    GROUP BY ACCOUNT_NO, ACCOUNT_BR
),
CHARGE_PRET AS (
    SELECT
        ACCOUNT_NO,
        ACCOUNT_BR,
        CONTRACT_REF_NO,
        (SUM(AMOUNT_DUE) - SUM(AMOUNT_PAID)) AS CHARGE_PRET_DUE
    FROM CFSFCUBS145.CSTB_AUTO_SETTLE_BLOCK b
    WHERE STATUS <> 'P'
      AND b.COMPONENT IN (
          'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT', 'MAIN_INT'
      )
      AND ACCOUNT_NO LIKE '251%'
    GROUP BY ACCOUNT_NO, ACCOUNT_BR, CONTRACT_REF_NO
)
SELECT
    e.BRANCH_CODE,
    c.CUSTOMER_ID,
    c.PRIMARY_APPLICANT_NAME,
    c.ACCOUNT_NUMBER,
    c.DR_PROD_AC,
    NVL(t.CHARGE_PRET_DUE, 0) AS CHARGE_PRET_DUE,
    NVL(r.CHARGE_DUE, 0) AS CHARGE_DUE,
    SUM(e.AMOUNT_DUE - e.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
    (
        NVL(t.CHARGE_PRET_DUE, 0)
        + NVL(r.CHARGE_DUE, 0)
        + SUM(e.AMOUNT_DUE - e.AMOUNT_SETTLED)
    ) AS ENCOURS_GLOBAL
FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES e
LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    ON c.ACCOUNT_NUMBER = e.ACCOUNT_NUMBER
LEFT JOIN CHARGE r
    ON r.ACCOUNT_NO = c.DR_PROD_AC
LEFT JOIN CHARGE_PRET t
    ON t.CONTRACT_REF_NO = c.ACCOUNT_NUMBER
WHERE e.COMPONENT_NAME = 'PRINCIPAL'
  AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
  AND c.CUSTOMER_ID = :customer_no
GROUP BY
    c.ACCOUNT_NUMBER,
    e.BRANCH_CODE,
    c.CUSTOMER_ID,
    c.PRIMARY_APPLICANT_NAME,
    c.DR_PROD_AC,
    t.CHARGE_PRET_DUE,
    r.CHARGE_DUE
;
