# Liste des agences depuis Flexcube STTM_BRANCH — BRANCH_CODE + BRANCH_NAME.

AGENCIES_FROM_STTM_BRANCH_SQL = """
SELECT DISTINCT
    b.BRANCH_CODE,
    b.BRANCH_NAME
FROM CFSFCUBS145.STTM_BRANCH b
WHERE b.BRANCH_CODE IS NOT NULL
  AND b.BRANCH_NAME IS NOT NULL
ORDER BY b.BRANCH_CODE, b.BRANCH_NAME
"""
