"""
Requêtes C360 (Customer 360) — Flexcube CFSFCUBS145.
Sources : Historique remboursements, Banque au quotidien, KYC.

Colonnes KYC (spec métier) :
CUSTOMER_NO, NUMERO_NAFA, CUSTOMER_PREFIX, CATEGORIE, CUSTOMER_TYPE, TYPE_1,
IDENTIFICATIONREGISTER, IDENTIFICATIONREGISTER_1, COUNTRY, LANGUAGE, GENRE,
MIDDLE_NAME, FIRST_NAME, FULL_NAME, DATE_OF_BIRTH, PLACE_OF_BIRTH, SEX,
P_NATIONAL_ID, PASSPORT_NO, PPT_ISS_DATE, PPT_EXP_DATE, D_ADDRESS1, E_MAIL,
MOB_ISD_NO, TELEPHONE, MOBILE_NUMBER, MOTHER_MAIDEN_NAME, SC_CUSTOMER_NO,
LOCAL_BRANCH, BRANCH_NAME, RECORD_STAT, DATE_CREATION, CUST_CAT, CUST_CAT_DESC,
UNIQUE_ID_NAME, UNIQUE_ID_VALUE
"""

_KYC_BODY = """
    SELECT
        p.CUSTOMER_NO,
        sc.EXT_REF_NO AS NUMERO_NAFA,
        p.CUSTOMER_PREFIX,
        DECODE(sc.CUSTOMER_TYPE, 'C', 'ENTREPRISE', 'I', 'PARTICULIER')
            || NVL(DECODE(p.sex, 'M', ' HOMME', 'F', ' FEMME'), '') AS CATEGORIE,
        sc.CUSTOMER_TYPE,
        DECODE(sc.CUSTOMER_TYPE, 'C', '2', 'I', '1') AS TYPE_1,
        '1' AS IDENTIFICATIONREGISTER,
        '1' AS IDENTIFICATIONREGISTER_1,
        sc.COUNTRY,
        sc.LANGUAGE,
        DECODE(p.sex, 'M', 'HOMME', 'F', 'FEMME') AS GENRE,
        p.MIDDLE_NAME,
        p.FIRST_NAME,
        sc.FULL_NAME,
        p.DATE_OF_BIRTH,
        p.PLACE_OF_BIRTH,
        p.SEX,
        p.P_NATIONAL_ID,
        p.PASSPORT_NO,
        p.PPT_ISS_DATE,
        p.PPT_EXP_DATE,
        p.D_ADDRESS1,
        p.E_MAIL,
        p.MOB_ISD_NO,
        p.TELEPHONE,
        p.MOBILE_NUMBER,
        p.MOTHER_MAIDEN_NAME,
        sc.CUSTOMER_NO AS SC_CUSTOMER_NO,
        sc.LOCAL_BRANCH,
        b.BRANCH_NAME,
        DECODE(sc.RECORD_STAT, 'O', 'OUVERT', 'C', 'FERME', sc.RECORD_STAT) AS RECORD_STAT,
        sc.CIF_CREATION_DATE AS DATE_CREATION,
        cat.CUST_CAT,
        cat.CUST_CAT_DESC,
        sc.UNIQUE_ID_NAME,
        sc.UNIQUE_ID_VALUE
    FROM CFSFCUBS145.STTM_CUSTOMER sc
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b
        ON b.BRANCH_CODE = sc.LOCAL_BRANCH
    LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
        ON sc.CUSTOMER_NO = p.CUSTOMER_NO
    LEFT JOIN CFSFCUBS145.STTM_CUST_CORPORATE c
        ON sc.CUSTOMER_NO = c.CUSTOMER_NO
    LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
        ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
"""

_KYC_SELECT = """
SELECT
    CUSTOMER_NO,
    NUMERO_NAFA,
    CUSTOMER_PREFIX,
    CATEGORIE,
    CUSTOMER_TYPE,
    TYPE_1,
    IDENTIFICATIONREGISTER,
    IDENTIFICATIONREGISTER_1,
    COUNTRY,
    LANGUAGE,
    GENRE,
    MIDDLE_NAME,
    FIRST_NAME,
    FULL_NAME,
    DATE_OF_BIRTH,
    PLACE_OF_BIRTH,
    SEX,
    P_NATIONAL_ID,
    PASSPORT_NO,
    PPT_ISS_DATE,
    PPT_EXP_DATE,
    D_ADDRESS1,
    E_MAIL,
    MOB_ISD_NO,
    TELEPHONE,
    MOBILE_NUMBER,
    MOTHER_MAIDEN_NAME,
    SC_CUSTOMER_NO,
    LOCAL_BRANCH,
    BRANCH_NAME,
    RECORD_STAT,
    DATE_CREATION,
    CUST_CAT,
    CUST_CAT_DESC,
    UNIQUE_ID_NAME,
    UNIQUE_ID_VALUE
"""

KYC_QUERY = f"""
WITH KYC AS (
{_KYC_BODY}
)
{_KYC_SELECT}
FROM KYC
WHERE CUSTOMER_NO = :customer_no
"""

KYC_BY_ACCOUNT_QUERY = f"""
WITH KYC AS (
{_KYC_BODY}
)
{_KYC_SELECT}
FROM KYC
WHERE CUSTOMER_NO IN (
    SELECT ca.CUST_NO
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
    WHERE ca.CUST_AC_NO = :lookup
)
FETCH FIRST 1 ROW ONLY
"""

KYC_BY_EXT_REF_QUERY = f"""
WITH KYC AS (
{_KYC_BODY}
)
{_KYC_SELECT}
FROM KYC
WHERE NUMERO_NAFA = :lookup
FETCH FIRST 1 ROW ONLY
"""

COMPTES_QUERY = """
WITH CHARGE AS (
    SELECT
        c.CUST_NO AS MATRICULE_CLIENT,
        b.ACCOUNT_BR AS CODE_AGENCE,
        b.ACCOUNT_NO AS NUMERO_COMPTE,
        NVL(SUM(NVL(b.AMOUNT_DUE, 0) - NVL(b.AMOUNT_PAID, 0)), 0) AS MONTANT_DUE
    FROM CFSFCUBS145.CSTB_AUTO_SETTLE_BLOCK b
    LEFT JOIN CFSFCUBS145.STTM_CUST_ACCOUNT c ON b.ACCOUNT_NO = c.CUST_AC_NO
    WHERE b.STATUS != 'P'
      AND c.CUST_NO = :customer_no
    GROUP BY c.CUST_NO, b.ACCOUNT_BR, b.ACCOUNT_NO
)
SELECT
    a.ACCOUNT_CODE,
    DECODE(
        a.ACCOUNT_CODE,
        '253', 'EPARGNE',
        '251', 'COURANT',
        '254', 'DEPOT_GARANTIE',
        '252', 'DAT',
        'AUTRE'
    ) AS TYPE_COMPTE,
    ca.CUST_AC_NO AS numero_Compte,
    ca.BRANCH_CODE AS agence_Compte,
    b.BRANCH_NAME,
    a.ACCOUNT_CLASS AS code_Type_Compte,
    a.DESCRIPTION AS type_Compte,
    bal.CURRENT_BALANCE AS solde_Comptable,
    bal.AVAILABLE_BALANCE AS solde_Net_Disponible,
    NVL(bal.CURRENT_BALANCE - bal.AVAILABLE_BALANCE, 0) AS montant_Indisponible,
    NVL(ch.MONTANT_DUE, 0) AS MONTANT_DUE,
    DECODE(ca.RECORD_STAT, 'O', 'Actif', 'C', 'Clôturé', 'I', 'Inactif', ca.RECORD_STAT) AS statut_Compte,
    TO_CHAR(ca.AC_OPEN_DATE, 'RRRR-MM-DD') AS date_Ouverture,
    TO_CHAR(SYSDATE, 'RRRR-MM-DD') AS date_Requete
FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS a ON ca.ACCOUNT_CLASS = a.ACCOUNT_CLASS
JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON ca.CUST_AC_NO = bal.CUST_AC_NO
JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = ca.BRANCH_CODE
LEFT JOIN CHARGE ch ON ca.CUST_AC_NO = ch.NUMERO_COMPTE
WHERE a.ACCOUNT_CODE IN ('253', '251', '254', '252')
  AND ca.CUST_NO = :customer_no
  AND ca.RECORD_STAT IN ('O', 'C', 'I')
ORDER BY ca.AC_OPEN_DATE DESC
"""

ECRITURES_QUERY = """
SELECT
    NVL(c.GL_DESC, s.AC_DESC) AS "Nom Client ",
    a.AC_NO AS "Numero Compte",
    DECODE(a.DRCR_IND, 'D', a.LCY_AMOUNT, 0) AS "Mouvement Debit",
    DECODE(a.DRCR_IND, 'C', a.LCY_AMOUNT, 0) AS "Mouvement Credit",
    TO_CHAR(a.TRN_DT, 'DD/MM/YYYY') AS "Date Comptable",
    TO_CHAR(a.VALUE_DT, 'DD/MM/YYYY') AS "Date Valeur",
    t.TRN_DESC AS "Libellé Ecriture",
    NVL(od.ADDL_TEXT, NVL(xx.ADDL_TEXT, d.DESCRIPTION)) AS "Libellé N° Batch"
FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES a
LEFT JOIN CFSFCUBS145.GLTM_GLMASTER c
    ON c.GL_CODE = a.AC_NO
LEFT JOIN CFSFCUBS145.STTM_CUST_ACCOUNT s
    ON s.CUST_AC_NO = a.AC_NO
LEFT JOIN CFSFCUBS145.STTM_TRN_CODE t
    ON t.TRN_CODE = a.TRN_CODE
LEFT JOIN CFSFCUBS145.STTM_BRANCH b
    ON b.BRANCH_CODE = a.AC_BRANCH
LEFT JOIN CFSFCUBS145.DETBS_JRNL_TXN_DETAIL xx
    ON a.TRN_REF_NO = xx.REFERENCE_NO
   AND a.EVENT_SR_NO = xx.SERIAL_NO
LEFT JOIN CFSFCUBS145.DETB_BATCH_MASTER d
    ON a.BATCH_NO = d.BATCH_NO
   AND a.AC_BRANCH = d.BRANCH_CODE
LEFT JOIN CFSFCUBS145.DETB_UPLOAD_DETAIL od
    ON od.BATCH_NO = a.BATCH_NO
   AND a.AC_BRANCH = od.ACCOUNT_BRANCH
   AND a.CURR_NO = od.CURR_NO
WHERE a.AC_NO = :account_no
ORDER BY a.AC_ENTRY_SR_NO DESC
FETCH FIRST :limit ROWS ONLY
"""

REMBOURSEMENTS_QUERY = """
SELECT
    a.AC_NO,
    NVL(c.GL_DESC, s.AC_DESC) AS DESCRIPTION,
    a.RELATED_ACCOUNT AS NO_PRET,
    DECODE(a.DRCR_IND, 'D', a.LCY_AMOUNT, 0) AS MOUVEMENT_DEBIT,
    DECODE(a.DRCR_IND, 'C', a.LCY_AMOUNT, 0) AS MOUVEMENT_CREDIT,
    TO_CHAR(a.TRN_DT, 'DD/MM/YYYY') AS DATE_SAISIE,
    TO_CHAR(a.VALUE_DT, 'DD/MM/YYYY') AS DATE_VALEUR,
    t.TRN_DESC,
    DECODE(
        a.AMOUNT_TAG,
        'MAIN_INT_SACL',   'REMBOURSEMENT INTERET',
        'MAIN_INT_LIQD',   'REMBOURSEMENT INTERET',
        'PRINCIPAL_LIQD',  'REMBOURSEMENT CAPITAL',
        'ODPR_PNTYT_LIQD', 'PENALITE CAPITAL',
        'ODIN_PNTYT_LIQD', 'PENALITE INTERET',
        a.AMOUNT_TAG
    ) AS LIBELLE_OPERATION
FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES a
LEFT JOIN CFSFCUBS145.GLTM_GLMASTER c ON c.GL_CODE = a.AC_NO
LEFT JOIN CFSFCUBS145.STTM_CUST_ACCOUNT s ON s.CUST_AC_NO = a.AC_NO
LEFT JOIN CFSFCUBS145.STTM_TRN_CODE t ON t.TRN_CODE = a.TRN_CODE
LEFT JOIN CFSFCUBS145.DETBS_JRNL_TXN_DETAIL xx
    ON a.TRN_REF_NO = xx.REFERENCE_NO AND a.EVENT_SR_NO = xx.SERIAL_NO
LEFT JOIN CFSFCUBS145.DETB_BATCH_MASTER d
    ON a.BATCH_NO = d.BATCH_NO AND a.AC_BRANCH = d.BRANCH_CODE
LEFT JOIN CFSFCUBS145.DETB_UPLOAD_DETAIL od
    ON od.BATCH_NO = a.BATCH_NO
   AND a.AC_BRANCH = od.ACCOUNT_BRANCH
   AND a.CURR_NO = od.CURR_NO
JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS cl ON cl.ACCOUNT_CLASS = s.ACCOUNT_CLASS
WHERE cl.ACCOUNT_CODE IN ('251')
  AND a.RELATED_ACCOUNT = :no_pret
  AND a.EVENT IN ('MLIQ', 'ALIQ')
ORDER BY a.AC_ENTRY_SR_NO DESC
"""

PRETS_CLIENT_QUERY = """
SELECT DISTINCT c.ACCOUNT_NUMBER AS NO_PRET
FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
WHERE c.CUSTOMER_ID = :customer_no
  AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
ORDER BY c.ACCOUNT_NUMBER
"""
