# Données clients : table DASH_RELATION (Cofina)
# Dernier MIGRATION_DATETIME du mois calendaire (MM/YYYY), comme les autres tables DASH.

CLIENTS_DASH_QUERY = """
SELECT
    CODE_BUREAU,
    AGENCE,
    NBRE_CLIENT_M,
    NBRE_CLIENT_M_1,
    VARIATION,
    VARIATION_POURCENT,
    FRAIS_OUV_CPT_M,
    FRAIS_OUV_CPT_M_1,
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_RELATION
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_RELATION d
    WHERE TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') = :month_year
)
ORDER BY CODE_BUREAU, AGENCE
"""
