# Nouveaux clients + frais d'ouverture — Flexcube CFSFCUBS145.
# Règles alignées sur comptes ouverts : ACCOUNT_CODE IN (251, 253),
# ACCOUNT_CLASS <> 25136, MAKER_ID <> APIUSER1.
# Dates : début inclusif, fin exclusive (YYYY-MM-DD).

CLIENTS_FLEXCUBE_QUERY = """
WITH CPT_OUVR AS (
    SELECT
        S.BRANCH_CODE,
        B.BRANCH_NAME,
        S.CUST_NO,
        S.CUST_AC_NO,
        S.AC_OPEN_DATE
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT S
    LEFT JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS AL
        ON AL.ACCOUNT_CLASS = S.ACCOUNT_CLASS
    LEFT JOIN CFSFCUBS145.STTM_BRANCH B
        ON B.BRANCH_CODE = S.BRANCH_CODE
    WHERE AL.ACCOUNT_CODE IN ('253', '251')
      AND S.ACCOUNT_CLASS <> '25136'
      AND NVL(S.MAKER_ID, 'X') <> 'APIUSER1'
      AND S.AC_OPEN_DATE >= TO_DATE(:date_m1_debut, 'YYYY-MM-DD')
      AND S.AC_OPEN_DATE <  TO_DATE(:date_m_fin_exclusive, 'YYYY-MM-DD')
),
CLIENTS_M AS (
    SELECT
        BRANCH_CODE,
        MAX(BRANCH_NAME) AS AGENCE,
        COUNT(DISTINCT CUST_NO) AS NBRE_CLIENT_M
    FROM CPT_OUVR
    WHERE AC_OPEN_DATE >= TO_DATE(:date_m_debut, 'YYYY-MM-DD')
      AND AC_OPEN_DATE <  TO_DATE(:date_m_fin_exclusive, 'YYYY-MM-DD')
    GROUP BY BRANCH_CODE
),
CLIENTS_M1 AS (
    SELECT
        BRANCH_CODE,
        MAX(BRANCH_NAME) AS AGENCE,
        COUNT(DISTINCT CUST_NO) AS NBRE_CLIENT_M_1
    FROM CPT_OUVR
    WHERE AC_OPEN_DATE >= TO_DATE(:date_m1_debut, 'YYYY-MM-DD')
      AND AC_OPEN_DATE <  TO_DATE(:date_m_debut, 'YYYY-MM-DD')
    GROUP BY BRANCH_CODE
),
FRAIS AS (
    SELECT
        C.BRANCH_CODE,
        C.AC_OPEN_DATE,
        NVL(SUM(B.AMOUNT_PAID), 0) AS FRAIS_PAYE
    FROM CPT_OUVR C
    LEFT JOIN CFSFCUBS145.CSTB_AUTO_SETTLE_BLOCK B
        ON B.ACCOUNT_NO = C.CUST_AC_NO
       AND B.PRODUCT = 'FOUV'
       AND B.COMPONENT = 'CHARGE'
    GROUP BY C.BRANCH_CODE, C.CUST_AC_NO, C.AC_OPEN_DATE
),
FRAIS_M AS (
    SELECT
        BRANCH_CODE,
        SUM(FRAIS_PAYE) AS FRAIS_OUV_CPT_M
    FROM FRAIS
    WHERE AC_OPEN_DATE >= TO_DATE(:date_m_debut, 'YYYY-MM-DD')
      AND AC_OPEN_DATE <  TO_DATE(:date_m_fin_exclusive, 'YYYY-MM-DD')
    GROUP BY BRANCH_CODE
),
FRAIS_M1 AS (
    SELECT
        BRANCH_CODE,
        SUM(FRAIS_PAYE) AS FRAIS_OUV_CPT_M_1
    FROM FRAIS
    WHERE AC_OPEN_DATE >= TO_DATE(:date_m1_debut, 'YYYY-MM-DD')
      AND AC_OPEN_DATE <  TO_DATE(:date_m_debut, 'YYYY-MM-DD')
    GROUP BY BRANCH_CODE
),
ALL_AGENCIES AS (
    SELECT BRANCH_CODE, AGENCE FROM CLIENTS_M
    UNION
    SELECT BRANCH_CODE, AGENCE FROM CLIENTS_M1
)
SELECT
    AA.BRANCH_CODE AS CODE_BUREAU,
    NVL(AA.AGENCE, B.BRANCH_NAME) AS AGENCE,
    NVL(CM.NBRE_CLIENT_M, 0) AS NBRE_CLIENT_M,
    NVL(CM1.NBRE_CLIENT_M_1, 0) AS NBRE_CLIENT_M_1,
    NVL(CM.NBRE_CLIENT_M, 0) - NVL(CM1.NBRE_CLIENT_M_1, 0) AS VARIATION,
    ROUND(
        (
            (NVL(CM.NBRE_CLIENT_M, 0) - NVL(CM1.NBRE_CLIENT_M_1, 0))
            / NULLIF(NVL(CM1.NBRE_CLIENT_M_1, 0), 0)
        ) * 100,
        2
    ) AS VARIATION_POURCENT,
    NVL(FM.FRAIS_OUV_CPT_M, 0) AS FRAIS_OUV_CPT_M,
    NVL(FM1.FRAIS_OUV_CPT_M_1, 0) AS FRAIS_OUV_CPT_M_1
FROM ALL_AGENCIES AA
LEFT JOIN CLIENTS_M CM ON CM.BRANCH_CODE = AA.BRANCH_CODE
LEFT JOIN CLIENTS_M1 CM1 ON CM1.BRANCH_CODE = AA.BRANCH_CODE
LEFT JOIN FRAIS_M FM ON FM.BRANCH_CODE = AA.BRANCH_CODE
LEFT JOIN FRAIS_M1 FM1 ON FM1.BRANCH_CODE = AA.BRANCH_CODE
LEFT JOIN CFSFCUBS145.STTM_BRANCH B ON B.BRANCH_CODE = AA.BRANCH_CODE
ORDER BY AA.BRANCH_CODE, AGENCE
"""
