# Collecte d'épargne à vue — requête métier validée (Flexcube CFSFCUBS145).
# Binds :date_debut / :date_fin_exclusive au format YYYY-MM-DD
# (début inclusif, fin exclusive = 1er jour du mois suivant).

COLLECTE_EPARGNE_A_VUE_QUERY = """
WITH ENCOURS_CLIENT AS (
    SELECT
        W.BRANCH_CODE,
        W.FIELD_CHAR_2,
        W.CUSTOMER_ID,
        W.DR_PROD_AC,
        W.PRIMARY_APPLICANT_NAME,
        W.ACCOUNT_NUMBER,
        W.AMOUNT_FINANCED,
        W.USER_DEFINED_STATUS,
        NVL(
            SUM(
                NVL(Z.AMOUNT_DUE, 0)
                - NVL(Z.AMOUNT_SETTLED, 0)
            ),
            0
        ) AS ENCOURS_TOTAL_M
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER W
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES Z
        ON Z.ACCOUNT_NUMBER = W.ACCOUNT_NUMBER
       AND Z.COMPONENT_NAME = 'PRINCIPAL'
    WHERE W.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND W.USER_DEFINED_STATUS IN ('NORM', 'IMMO')
    GROUP BY
        W.BRANCH_CODE,
        W.FIELD_CHAR_2,
        W.CUSTOMER_ID,
        W.DR_PROD_AC,
        W.PRIMARY_APPLICANT_NAME,
        W.ACCOUNT_NUMBER,
        W.AMOUNT_FINANCED,
        W.USER_DEFINED_STATUS
),
OBJ_COL_EPV AS (
    SELECT
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME,
        ACCOUNT_NUMBER,
        AMOUNT_FINANCED,
        USER_DEFINED_STATUS,
        ENCOURS_TOTAL_M,
        CASE
            WHEN AMOUNT_FINANCED <= 10000000
                THEN ROUND(ENCOURS_TOTAL_M * 0.10, 0)
            WHEN AMOUNT_FINANCED > 10000000
                THEN ROUND(ENCOURS_TOTAL_M * 0.50, 0)
            ELSE 0
        END AS OBJ_COL_EPV_VUE
    FROM ENCOURS_CLIENT
),
OBJ_COL_EP_VUE_F AS (
    SELECT
        BRANCH_CODE AS CODE_AGENCE,
        FIELD_CHAR_2 AS CODE_CAF,
        CUSTOMER_ID AS MATRICULE_CLIENT,
        DR_PROD_AC AS NUMERO_COMPTE,
        PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        SUM(AMOUNT_FINANCED) AS CUM_MONTANT_FINANCE,
        SUM(ENCOURS_TOTAL_M) AS CUM_ENCOURS_CREDIT,
        SUM(OBJ_COL_EPV_VUE) AS OBJ_COL_EPV_VUE
    FROM OBJ_COL_EPV
    GROUP BY
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME
),
DEPOT AS (
    SELECT
        A.RELATED_CUSTOMER,
        A.AC_NO,
        COUNT(A.TRN_REF_NO) AS NB_TRANSACTIONS,
        SUM(A.LCY_AMOUNT) AS TOTAL_VERSEMENTS
    FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES A
    INNER JOIN CFSFCUBS145.STTM_CUST_ACCOUNT CPT
        ON A.AC_NO = CPT.CUST_AC_NO
    INNER JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS CL
        ON CPT.ACCOUNT_CLASS = CL.ACCOUNT_CLASS
    WHERE CL.ACCOUNT_CODE IN ('251', '253')
      AND A.DRCR_IND = 'C'
      AND A.TRN_CODE IN (
            '001', '310', '320', '315', '317',
            '301', '303', '094', '510'
      )
      AND A.MODULE <> 'CL'
      AND A.VALUE_DT >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND A.VALUE_DT <  TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
    GROUP BY
        A.RELATED_CUSTOMER,
        A.AC_NO
),
DEPOT_CLIENT AS (
    SELECT
        RELATED_CUSTOMER AS MATRICULE_CLIENT,
        SUM(TOTAL_VERSEMENTS) AS TOTAL_DEPOT
    FROM DEPOT
    GROUP BY RELATED_CUSTOMER
),
PENALITE AS (
    SELECT
        Z.ACCOUNT_NUMBER AS NO_PRET,
        Z.SCHEDULE_NO,
        SUM(NVL(Z.AMOUNT_DUE, 0)) AS TOTAL_PENALITE,
        SUM(NVL(Z.AMOUNT_SETTLED, 0)) AS TOTAL_PENALITE_PAYE,
        SUM(
            NVL(Z.AMOUNT_DUE, 0)
            - NVL(Z.AMOUNT_SETTLED, 0)
        ) AS TOTAL_PENALITE_RESTANT
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES Z
    INNER JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER C
        ON C.ACCOUNT_NUMBER = Z.ACCOUNT_NUMBER
    WHERE C.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND Z.COMPONENT_NAME IN (
            'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT'
      )
    GROUP BY
        Z.ACCOUNT_NUMBER,
        Z.SCHEDULE_NO
),
BASE AS (
    SELECT
        S.ACCOUNT_NUMBER,
        S.SCHEDULE_NO,
        S.SCHEDULE_DUE_DATE,
        SUM(NVL(S.AMOUNT_DUE, 0)) AS MONTANT_ECHEANCE,
        SUM(NVL(S.AMOUNT_SETTLED, 0)) AS MONTANT_ECHEANCE_PAYE,
        SUM(
            CASE
                WHEN S.SCHEDULE_DUE_DATE > TRUNC(SYSDATE)
                THEN 0
                ELSE NVL(S.AMOUNT_DUE, 0) - NVL(S.AMOUNT_SETTLED, 0)
            END
        ) AS MONTANT_ECHEANCE_IMPY
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES S
    WHERE S.COMPONENT_NAME IN ('MAIN_INT', 'PRINCIPAL')
    GROUP BY
        S.ACCOUNT_NUMBER,
        S.SCHEDULE_NO,
        S.SCHEDULE_DUE_DATE
),
FINAL AS (
    SELECT
        B.ACCOUNT_NUMBER,
        B.SCHEDULE_NO,
        B.SCHEDULE_DUE_DATE,
        B.MONTANT_ECHEANCE,
        B.MONTANT_ECHEANCE_PAYE,
        B.MONTANT_ECHEANCE_IMPY,
        NVL(P.TOTAL_PENALITE_RESTANT, 0) AS PENALITE,
        NVL(B.MONTANT_ECHEANCE_IMPY, 0)
        + NVL(P.TOTAL_PENALITE_RESTANT, 0) AS EXIGIBLE,
        CASE
            WHEN NVL(B.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(P.TOTAL_PENALITE_RESTANT, 0) > 0
            THEN 'I'
            WHEN NVL(B.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(P.TOTAL_PENALITE_RESTANT, 0) = 0
             AND B.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
            THEN 'R'
            WHEN NVL(B.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(P.TOTAL_PENALITE_RESTANT, 0) = 0
             AND B.SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
            THEN 'A'
            ELSE NULL
        END AS STATUS
    FROM BASE B
    LEFT JOIN PENALITE P
        ON P.NO_PRET = B.ACCOUNT_NUMBER
       AND P.SCHEDULE_NO = B.SCHEDULE_NO
),
TA AS (
    SELECT
        ACCOUNT_NUMBER,
        SCHEDULE_DUE_DATE,
        MONTANT_ECHEANCE,
        MONTANT_ECHEANCE_PAYE,
        MONTANT_ECHEANCE_IMPY,
        PENALITE,
        EXIGIBLE,
        STATUS
    FROM FINAL
    WHERE SCHEDULE_DUE_DATE >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND SCHEDULE_DUE_DATE <  TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
),
TA_M AS (
    SELECT
        C.BRANCH_CODE,
        C.CUSTOMER_ID,
        SUM(T.MONTANT_ECHEANCE) AS MONTANT_ECHEANCE
    FROM TA T
    INNER JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER C
        ON C.ACCOUNT_NUMBER = T.ACCOUNT_NUMBER
    WHERE C.USER_DEFINED_STATUS IN ('NORM', 'IMMO')
      AND NVL(C.PRODUCT_CODE, 'XXX') NOT LIKE 'RA%'
    GROUP BY
        C.BRANCH_CODE,
        C.CUSTOMER_ID
),
GESTIONNAIRE_CAF AS (
    SELECT
        P.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        MAX(U.LOV_DESC) AS CHARGE_AFFAIRE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER P
    LEFT JOIN CFSFCUBS145.UDTM_LOV U
        ON U.FIELD_NAME = 'GESTION_PRET'
       AND U.LOV = P.FIELD_CHAR_2
    GROUP BY P.FIELD_CHAR_2
),
COLLECTE_A_VUE AS (
    SELECT
        V.CODE_AGENCE,
        V.CODE_CAF,
        V.MATRICULE_CLIENT,
        V.NUMERO_COMPTE,
        V.NOM_CLIENT,
        V.CUM_MONTANT_FINANCE,
        V.CUM_ENCOURS_CREDIT,
        V.OBJ_COL_EPV_VUE,
        NVL(T.MONTANT_ECHEANCE, 0) AS MONTANT_ECHEANCE,
        NVL(D.TOTAL_DEPOT, 0) AS TOTAL_DEPOT,
        CASE
            WHEN NVL(D.TOTAL_DEPOT, 0) - NVL(T.MONTANT_ECHEANCE, 0) <= 0
            THEN 0
            ELSE NVL(D.TOTAL_DEPOT, 0) - NVL(T.MONTANT_ECHEANCE, 0)
        END AS COL_EP_VUE
    FROM OBJ_COL_EP_VUE_F V
    LEFT JOIN DEPOT_CLIENT D
        ON D.MATRICULE_CLIENT = V.MATRICULE_CLIENT
    LEFT JOIN TA_M T
        ON T.CUSTOMER_ID = V.MATRICULE_CLIENT
)
SELECT
    V.CODE_AGENCE,
    B.BRANCH_NAME,
    V.CODE_CAF,
    G.CHARGE_AFFAIRE,
    V.MATRICULE_CLIENT,
    V.NUMERO_COMPTE,
    V.NOM_CLIENT,
    V.CUM_MONTANT_FINANCE,
    V.CUM_ENCOURS_CREDIT,
    V.OBJ_COL_EPV_VUE,
    V.MONTANT_ECHEANCE,
    V.TOTAL_DEPOT,
    V.COL_EP_VUE
FROM COLLECTE_A_VUE V
LEFT JOIN GESTIONNAIRE_CAF G
    ON G.CODE_GESTION_PRET = V.CODE_CAF
LEFT JOIN CFSFCUBS145.STTM_BRANCH B
    ON B.BRANCH_CODE = V.CODE_AGENCE
ORDER BY
    V.CODE_AGENCE,
    V.CODE_CAF,
    V.MATRICULE_CLIENT
"""
