# Collecte d'épargne à vue — Flexcube CFSFCUBS145.
# Binds :date_debut / :date_fin_exclusive (YYYY-MM-DD, fin exclusive).
# Périmètre ENCOURS_CLIENT : hors rebooker, hors restructuration,
# hors prêts RA / 25136, hors prêts protocole (FIELD_CHAR_13 like PC%).

COLLECTE_EPARGNE_A_VUE_QUERY = """
WITH ENCOURS AS (
    SELECT
        w.BRANCH_CODE,
        w.FIELD_CHAR_2,
        w.CUSTOMER_ID,
        w.DR_PROD_AC,
        w.PRIMARY_APPLICANT_NAME,
        w.ACCOUNT_NUMBER,
        w.AMOUNT_FINANCED,
        w.USER_DEFINED_STATUS,
        w.FIELD_CHAR_10 AS REFERENCE_COMITE,
        NVL(w.FIELD_CHAR_13, 'NO') AS ID_PROTOCOLES,
        NVL(w.FIELD_CHAR_19, 'NO') AS REBOOKER,
        w.FIELD_CHAR_14 AS ID_LIGNE_FINANCEMENT,
        NVL(w.FIELD_CHAR_7, 'NO') AS CODE_REF_CREDIT_RESTRUCTURE,
        w.FIELD_NUMBER_5 AS NO_CONTRAT_RESTRUCTURE,
        SUM(
            NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)
        ) AS ENCOURS_TOTAL_M,
        SUM(
            CASE
                WHEN w.USER_DEFINED_STATUS IN ('NORM', 'IMPA')
                THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)
                ELSE 0
            END
        ) AS ENCOURS_SAIN_M,
        SUM(
            CASE
                WHEN w.USER_DEFINED_STATUS NOT IN ('NORM', 'IMPA')
                THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)
                ELSE 0
            END
        ) AS ENCOURS_IMPAYE_M
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER w
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = w.ACCOUNT_NUMBER
       AND z.COMPONENT_NAME = 'PRINCIPAL'
    WHERE w.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND w.USER_DEFINED_STATUS IN ('NORM', 'IMMO')
      AND w.ACCOUNT_NUMBER NOT LIKE '%RA%'
      AND w.DR_PROD_AC NOT IN (
            SELECT CUST_AC_NO
            FROM CFSFCUBS145.STTM_CUST_ACCOUNT
            WHERE ACCOUNT_CLASS = '25136'
      )
    GROUP BY
        w.BRANCH_CODE,
        w.FIELD_CHAR_2,
        w.CUSTOMER_ID,
        w.DR_PROD_AC,
        w.PRIMARY_APPLICANT_NAME,
        w.ACCOUNT_NUMBER,
        w.AMOUNT_FINANCED,
        w.USER_DEFINED_STATUS,
        w.FIELD_CHAR_13,
        w.FIELD_CHAR_14,
        w.FIELD_NUMBER_5,
        w.FIELD_CHAR_7,
        w.FIELD_CHAR_10,
        w.FIELD_CHAR_19
),
ENCOURS_CLIENT AS (
    SELECT *
    FROM ENCOURS
    WHERE REBOOKER != 'YES'
      AND ID_PROTOCOLES NOT LIKE 'PC%'
      AND CODE_REF_CREDIT_RESTRUCTURE != 'YES'
),
OBJ_COL_EPV_LIM_DEX AS (
    SELECT
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME,
        ACCOUNT_NUMBER,
        AMOUNT_FINANCED,
        USER_DEFINED_STATUS,
        ENCOURS_TOTAL_M,
        ROUND(ENCOURS_TOTAL_M * 0.10, 0) AS OBJ_COL_EPV_VUE
    FROM ENCOURS_CLIENT
    WHERE AMOUNT_FINANCED <= 10000000
),
OBJ_COL_EPV_SUP_LIM_DEX AS (
    SELECT
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME,
        ACCOUNT_NUMBER,
        AMOUNT_FINANCED,
        USER_DEFINED_STATUS,
        ENCOURS_TOTAL_M,
        ROUND(ENCOURS_TOTAL_M * 0.5, 0) AS OBJ_COL_EPV_VUE
    FROM ENCOURS_CLIENT
    WHERE AMOUNT_FINANCED > 10000000
),
OBJ_COL_EP_VUE AS (
    SELECT * FROM OBJ_COL_EPV_SUP_LIM_DEX
    UNION
    SELECT * FROM OBJ_COL_EPV_LIM_DEX
),
OBJ_COL_EP_VUE_F AS (
    SELECT
        BRANCH_CODE AS CODE_AGENCE,
        FIELD_CHAR_2 AS CODE_CAF,
        CUSTOMER_ID AS MATRICULE_CLIENT,
        DR_PROD_AC AS NUMERO_COMPTE,
        PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        SUM(AMOUNT_FINANCED) AS CUM_MONTANT_FINANCE,
        SUM(ENCOURS_TOTAL_M) AS CUM_ENCOURS_CREDIT,
        SUM(OBJ_COL_EPV_VUE) AS OBJ_COL_EPV_VUE
    FROM OBJ_COL_EP_VUE
    GROUP BY
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME,
        AMOUNT_FINANCED
),
DEPOT AS (
    SELECT
        CPT.CUST_NO,
        A.AC_NO,
        COUNT(A.TRN_REF_NO) AS NB_TRANSACTIONS,
        SUM(A.LCY_AMOUNT) AS TOTAL_VERSEMENTS
    FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES A
    JOIN CFSFCUBS145.STTM_CUST_ACCOUNT CPT
        ON A.AC_NO = CPT.CUST_AC_NO
    JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS CL
        ON CPT.ACCOUNT_CLASS = CL.ACCOUNT_CLASS
    WHERE CL.ACCOUNT_CODE IN ('251', '253')
      AND A.DRCR_IND = 'C'
      AND A.TRN_CODE IN (
            '001', '310', '320', '315', '317',
            '301', '303', '094', '510'
      )
      AND A.MODULE NOT IN ('CL')
      AND A.VALUE_DT >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND A.VALUE_DT <  TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
    GROUP BY
        CPT.CUST_NO,
        A.AC_NO
),
DEPOT_CLIENT AS (
    SELECT
        CUST_NO AS MATRICULE_CLIENT,
        SUM(TOTAL_VERSEMENTS) AS TOTAL_DEPOT
    FROM DEPOT
    GROUP BY CUST_NO
),
PENALITE AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        z.SCHEDULE_NO,
        SUM(NVL(z.AMOUNT_DUE, 0)) AS TOTAL_PENALITE,
        SUM(NVL(z.AMOUNT_SETTLED, 0)) AS TOTAL_PENALITE_PAYE,
        SUM(
            NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)
        ) AS TOTAL_PENALITE_RESTANT
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME IN (
            'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT'
      )
    GROUP BY
        c.ACCOUNT_NUMBER,
        z.SCHEDULE_NO
),
BASE AS (
    SELECT
        ACCOUNT_NUMBER,
        SCHEDULE_DUE_DATE,
        SUM(NVL(AMOUNT_DUE, 0)) AS MONTANT_ECHEANCE,
        SUM(NVL(AMOUNT_SETTLED, 0)) AS MONTANT_ECHEANCE_PAYE,
        SUM(
            CASE
                WHEN SCHEDULE_DUE_DATE > TRUNC(SYSDATE) THEN 0
                ELSE NVL(AMOUNT_DUE, 0) - NVL(AMOUNT_SETTLED, 0)
            END
        ) AS MONTANT_ECHEANCE_IMPY
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
    WHERE COMPONENT_NAME IN ('MAIN_INT', 'PRINCIPAL')
    GROUP BY
        ACCOUNT_NUMBER,
        SCHEDULE_DUE_DATE
),
BASE_NUM AS (
    SELECT
        e.*,
        ROW_NUMBER() OVER (
            PARTITION BY e.ACCOUNT_NUMBER
            ORDER BY e.SCHEDULE_DUE_DATE
        ) AS NUMERO_ECHEANCE
    FROM BASE e
),
FINAL AS (
    SELECT
        e.ACCOUNT_NUMBER,
        e.SCHEDULE_DUE_DATE,
        e.NUMERO_ECHEANCE,
        e.MONTANT_ECHEANCE,
        e.MONTANT_ECHEANCE_PAYE,
        e.MONTANT_ECHEANCE_IMPY,
        NVL(pen.TOTAL_PENALITE_RESTANT, 0) AS PENALITE,
        NVL(e.MONTANT_ECHEANCE_IMPY, 0)
            + NVL(pen.TOTAL_PENALITE_RESTANT, 0) AS EXIGIBLE,
        CASE
            WHEN NVL(e.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(pen.TOTAL_PENALITE_RESTANT, 0) > 0
            THEN 'I'
            WHEN NVL(e.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(pen.TOTAL_PENALITE_RESTANT, 0) = 0
             AND e.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
            THEN 'R'
            WHEN NVL(e.MONTANT_ECHEANCE_IMPY, 0)
               + NVL(pen.TOTAL_PENALITE_RESTANT, 0) = 0
             AND e.SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
            THEN 'A'
            ELSE NULL
        END AS STATUS
    FROM BASE_NUM e
    LEFT JOIN PENALITE pen
        ON pen.NO_PRET = e.ACCOUNT_NUMBER
       AND pen.SCHEDULE_NO = e.NUMERO_ECHEANCE
),
TA AS (
    SELECT *
    FROM FINAL
    WHERE SCHEDULE_DUE_DATE >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND SCHEDULE_DUE_DATE <  TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
),
TA_M AS (
    SELECT
        c.BRANCH_CODE,
        c.CUSTOMER_ID,
        c.PRIMARY_APPLICANT_NAME,
        SUM(z.MONTANT_ECHEANCE) AS MONTANT_ECHEANCE
    FROM TA z
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER c
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.USER_DEFINED_STATUS IN ('NORM', 'IMMO')
      AND c.PRODUCT_CODE NOT LIKE 'RA%'
    GROUP BY
        c.BRANCH_CODE,
        c.CUSTOMER_ID,
        c.PRIMARY_APPLICANT_NAME
),
GESTIONNAIRE_CAF AS (
    SELECT
        P.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        MAX(U.LOV_DESC) AS CHARGE_AFFAIRE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER P
    LEFT JOIN CFSFCUBS145.UDTM_LOV U
        ON U.FIELD_NAME = 'GESTION_PRET'
       AND U.LOV = P.FIELD_CHAR_2
    GROUP BY P.FIELD_CHAR_2
),
COLLECTE_A_VUE AS (
    SELECT
        V.CODE_AGENCE,
        V.CODE_CAF,
        V.MATRICULE_CLIENT,
        V.NUMERO_COMPTE,
        V.NOM_CLIENT,
        V.CUM_MONTANT_FINANCE,
        V.CUM_ENCOURS_CREDIT,
        V.OBJ_COL_EPV_VUE,
        NVL(T.MONTANT_ECHEANCE, 0) AS MONTANT_ECHEANCE,
        NVL(D.TOTAL_DEPOT, 0) AS TOTAL_DEPOT,
        CASE
            WHEN NVL(D.TOTAL_DEPOT, 0) - NVL(T.MONTANT_ECHEANCE, 0) <= 0
            THEN 0
            ELSE NVL(D.TOTAL_DEPOT, 0) - NVL(T.MONTANT_ECHEANCE, 0)
        END AS COL_EP_VUE
    FROM OBJ_COL_EP_VUE_F V
    LEFT JOIN DEPOT_CLIENT D
        ON D.MATRICULE_CLIENT = V.MATRICULE_CLIENT
    LEFT JOIN TA_M T
        ON T.CUSTOMER_ID = V.MATRICULE_CLIENT
)
SELECT
    V.CODE_AGENCE,
    B.BRANCH_NAME,
    V.CODE_CAF,
    G.CHARGE_AFFAIRE,
    V.MATRICULE_CLIENT,
    V.NUMERO_COMPTE,
    V.NOM_CLIENT,
    V.CUM_MONTANT_FINANCE,
    V.CUM_ENCOURS_CREDIT,
    V.OBJ_COL_EPV_VUE,
    V.MONTANT_ECHEANCE,
    V.TOTAL_DEPOT,
    V.COL_EP_VUE
FROM COLLECTE_A_VUE V
LEFT JOIN GESTIONNAIRE_CAF G
    ON G.CODE_GESTION_PRET = V.CODE_CAF
LEFT JOIN CFSFCUBS145.STTM_BRANCH B
    ON B.BRANCH_CODE = V.CODE_AGENCE
ORDER BY
    V.CODE_AGENCE,
    V.CODE_CAF,
    V.MATRICULE_CLIENT
"""
