# Ouvertures de comptes (251 = courants, 253 = épargne).
# Règles métier : ACCOUNT_CODE IN (251, 253), ACCOUNT_CLASS <> 25136,
# MAKER_ID <> APIUSER1. Dates : début inclusif, fin exclusive.

COMPTES_OUVERTS_MENSUEL_QUERY = """
WITH CPT_OUVR AS (
    SELECT
        S.BRANCH_CODE,
        B.BRANCH_NAME,
        S.CUST_AC_NO,
        AL.ACCOUNT_CODE,
        EXTRACT(MONTH FROM S.AC_OPEN_DATE) AS MOIS
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT S
    LEFT JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS AL
        ON AL.ACCOUNT_CLASS = S.ACCOUNT_CLASS
    LEFT JOIN CFSFCUBS145.STTM_BRANCH B
        ON B.BRANCH_CODE = S.BRANCH_CODE
    WHERE AL.ACCOUNT_CODE IN ('253', '251')
      AND S.ACCOUNT_CLASS <> '25136'
      AND NVL(S.MAKER_ID, 'X') <> 'APIUSER1'
      AND S.AC_OPEN_DATE >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND S.AC_OPEN_DATE <  TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
)
SELECT
    BRANCH_CODE,
    BRANCH_NAME,
    MOIS,
    COUNT(CUST_AC_NO) AS REALISE,
    SUM(CASE WHEN ACCOUNT_CODE = '251' THEN 1 ELSE 0 END) AS REALISE_251,
    SUM(CASE WHEN ACCOUNT_CODE = '253' THEN 1 ELSE 0 END) AS REALISE_253
FROM CPT_OUVR
GROUP BY BRANCH_CODE, BRANCH_NAME, MOIS
ORDER BY BRANCH_CODE, MOIS
"""
