
ENCOURS_EPARGNE_DASH_QUERY = """
SELECT
    BRANCH_CODE,
    BRANCH_NAME,
    ENCOURS_TOTAL_M,
    M_ENCOURS_EPARGNE_SIMPLE,
    M1_ENCOURS_EPARGNE_SIMPLE,
    M_ENCOURS_CPT_EPARGNE_PROJET,
    M1_ENCOURS_CPT_EPARGNE_PROJET,
    DETES_RATT_EPARGNE_SIMPLE_M,
    DETES_RATT_EPARGNE_SIMPLE_M1,
    DETES_RATT_EPARGNE_SPROJET_M,
    DETES_RATT_EPARGNE_SPROJET_M1,
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_ENCOURS_EPARGNE
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_ENCOURS_EPARGNE d
    WHERE TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') = :month_year
)
ORDER BY BRANCH_CODE, BRANCH_NAME
"""
