# Requête SQL Entrées PAR et Provisions
# __DATE_REF__ : date de référence (format DD/MM/YYYY)
# __WHERE_DUREE__ : condition sur DUREE_IMPAYE_A_DATE selon le palier PAR (ex: "> 0 AND DUREE_IMPAYE_A_DATE <= 30")

ENTREES_PAR_QUERY = """
WITH ENCOURS_COFINA AS (
    SELECT
        ACCOUNT_NUMBER,
        SUM(AMOUNT_DUE - AMOUNT_SETTLED) AS ENCOURS_TOTAL,
        SUM(CASE WHEN SCHEDULE_DUE_DATE >= TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN AMOUNT_DUE ELSE 0 END) AS ENCOURS_SAIN,
        SUM(CASE WHEN SCHEDULE_DUE_DATE < TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN AMOUNT_DUE - AMOUNT_SETTLED ELSE 0 END) AS ENCOURS_IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
    WHERE COMPONENT_NAME IN ('PRINCIPAL')
    GROUP BY ACCOUNT_NUMBER
),
UDF_PRET AS (
    SELECT
        P.ACCOUNT_NUMBER,
        (SELECT MAX(U.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV U WHERE U.FIELD_NAME = 'TYPE_PRODUIT' AND U.LOV = P.FIELD_CHAR_17) AS TYPE_PRODUIT,
        (SELECT MAX(U.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV U WHERE U.FIELD_NAME = 'BLOC' AND U.LOV = P.FIELD_CHAR_15) AS BLOC,
        (SELECT MAX(U.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV U WHERE U.FIELD_NAME = 'GESTION_PRET' AND U.LOV = P.FIELD_CHAR_2) AS CHARGE_AFFAIRE,
        DECODE(P.ACCOUNT_STATUS, 'A', 'FINANCER', 'L', 'SOLDER', 'V', 'Annuler', 'Y', 'Futur Deblocage', 'H', 'EN ATTENTE') AS STATUT_PRET,
        P.FIELD_CHAR_17 AS CODE_TYPE_PRODUIT
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER P
),
ENTREE_PAR AS (
    SELECT
        P.ACCOUNT_NUMBER AS NO_PRET,
        UD.BLOC,
        P.USER_DEFINED_STATUS AS STATUT_DECLASSEMENT,
        P.PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        P.BOOK_DATE AS DATE_MISE_EN_PLACE,
        P.BRANCH_CODE AS CODE_AGENCE,
        B.BRANCH_NAME AS AGENCE,
        P.AMOUNT_FINANCED AS PRODUCTION_EN_VOLUME,
        (SELECT MIN(SC.SCHEDULE_DUE_DATE) FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES SC WHERE SC.ACCOUNT_NUMBER = P.ACCOUNT_NUMBER AND SC.COMPONENT_NAME = 'MAIN_INT') AS DATE_PREM_ECHEANCE,
        EC.ENCOURS_TOTAL,
        EC.ENCOURS_SAIN,
        EC.ENCOURS_IMPAYE,
        NVL((TO_DATE('__DATE_REF__', 'DD/MM/YYYY') - TO_DATE((SELECT MIN(Z.SCHEDULE_DUE_DATE) FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES Z WHERE Z.ACCOUNT_NUMBER = P.ACCOUNT_NUMBER AND Z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT') AND Z.SCHEDULE_DUE_DATE <= TO_DATE('__DATE_REF__', 'DD/MM/YYYY') AND ((Z.AMOUNT_DUE - Z.AMOUNT_SETTLED) > 0) AND P.ACCOUNT_STATUS NOT IN ('L', 'V')))), 0) AS DUREE_IMPAYE_A_DATE,
        CASE
            WHEN P.USER_DEFINED_STATUS = 'DSL2' THEN (EC.ENCOURS_TOTAL * 40) / 100
            WHEN P.USER_DEFINED_STATUS = 'DCL3' THEN (EC.ENCOURS_TOTAL * 80) / 100
            WHEN P.USER_DEFINED_STATUS = 'DSCL4' THEN EC.ENCOURS_TOTAL
            ELSE EC.ENCOURS_TOTAL
        END AS PROVISIONS
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER P
    LEFT JOIN UDF_PRET UD ON UD.ACCOUNT_NUMBER = P.ACCOUNT_NUMBER
    LEFT JOIN ENCOURS_COFINA EC ON EC.ACCOUNT_NUMBER = P.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.STTM_BRANCH B ON B.BRANCH_CODE = P.BRANCH_CODE
)
SELECT * FROM ENTREE_PAR WHERE __WHERE_DUREE__
"""

# Filtres DUREE_IMPAYE_A_DATE par palier PAR (en jours)
PAR_FILTERS = {
    0:   "DUREE_IMPAYE_A_DATE = 1",
    30:  "DUREE_IMPAYE_A_DATE = 31",
    90:  "DUREE_IMPAYE_A_DATE = 91",
    180: "DUREE_IMPAYE_A_DATE = 181",
    360: "DUREE_IMPAYE_A_DATE = 361",
}


def get_query_entrees_par(date_str: str, par_bucket: int):
    """
    Retourne la requête Entrées PAR pour une date et un palier PAR.
    par_bucket: 0, 30, 90, 180 ou 360
    """
    if par_bucket not in PAR_FILTERS:
        raise ValueError("par_bucket doit être 0, 30, 90, 180 ou 360")
    where = PAR_FILTERS[par_bucket]
    return ENTREES_PAR_QUERY.replace("__DATE_REF__", date_str).replace("__WHERE_DUREE__", where)
