# Tables DASH MoneyGram (Cofina) — même snapshot que OM / Wave / Ria.


def sql_dash_envoi_moneygram(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_ENVOIE_MONEYGRAM_M_1,
    VOLUME_ENVOIE_MONEYGRAM_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_ENVOIE_MONEYGRAM
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_ENVOIE_MONEYGRAM d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""


def sql_dash_paiement_moneygram(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_PAIEMENT_MONEYGRAM_M_1,
    VOLUME_PAIEMENT_MONEYGRAM_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_PAIEMENT_MONEYGRAM
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_PAIEMENT_MONEYGRAM d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""
