# Objectifs collecte épargne à vue — snapshot mensuel (Flexcube).
# Pas de filtre date : photo des encours / objectifs à l'instant T (typiquement le 1er du mois).

OBJECTIF_EPV_VUE_SNAPSHOT_QUERY = """
WITH ENCOURS AS (
    SELECT
        W.BRANCH_CODE,
        W.FIELD_CHAR_2,
        W.CUSTOMER_ID,
        W.DR_PROD_AC,
        W.PRIMARY_APPLICANT_NAME,
        W.ACCOUNT_NUMBER,
        W.AMOUNT_FINANCED,
        W.USER_DEFINED_STATUS,
        NVL(W.FIELD_CHAR_13, 'NO') AS ID_PROTOCOLES,
        NVL(W.FIELD_CHAR_19, 'NO') AS REBOOKER,
        NVL(W.FIELD_CHAR_7, 'NO') AS CODE_REF_CREDIT_RESTRUCTURE,
        NVL(
            SUM(
                NVL(Z.AMOUNT_DUE, 0)
                - NVL(Z.AMOUNT_SETTLED, 0)
            ),
            0
        ) AS ENCOURS_TOTAL_M
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER W
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES Z
        ON Z.ACCOUNT_NUMBER = W.ACCOUNT_NUMBER
       AND Z.COMPONENT_NAME = 'PRINCIPAL'
    WHERE W.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND W.USER_DEFINED_STATUS IN ('NORM', 'IMMO')
      AND W.ACCOUNT_NUMBER NOT LIKE '%RA%'
      AND W.DR_PROD_AC NOT IN (
            SELECT CUST_AC_NO
            FROM CFSFCUBS145.STTM_CUST_ACCOUNT
            WHERE ACCOUNT_CLASS = '25136'
      )
    GROUP BY
        W.BRANCH_CODE,
        W.FIELD_CHAR_2,
        W.CUSTOMER_ID,
        W.DR_PROD_AC,
        W.PRIMARY_APPLICANT_NAME,
        W.ACCOUNT_NUMBER,
        W.AMOUNT_FINANCED,
        W.USER_DEFINED_STATUS,
        W.FIELD_CHAR_13,
        W.FIELD_CHAR_19,
        W.FIELD_CHAR_7
),
ENCOURS_CLIENT AS (
    SELECT *
    FROM ENCOURS
    WHERE REBOOKER != 'YES'
      AND ID_PROTOCOLES NOT LIKE 'PC%'
      AND CODE_REF_CREDIT_RESTRUCTURE != 'YES'
      AND CUSTOMER_ID NOT IN (
            SELECT DISTINCT CUSTOMER_ID
            FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER
            WHERE FIELD_CHAR_13 LIKE 'PC%'
      )
),
OBJ_COL_EPV AS (
    SELECT
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME,
        AMOUNT_FINANCED,
        ENCOURS_TOTAL_M,
        CASE
            WHEN AMOUNT_FINANCED <= 10000000
                THEN ROUND(ENCOURS_TOTAL_M * 0.10, 0)
            WHEN AMOUNT_FINANCED > 10000000
                THEN ROUND(ENCOURS_TOTAL_M * 0.50, 0)
            ELSE 0
        END AS OBJ_COL_EPV_VUE
    FROM ENCOURS_CLIENT
),
OBJ_COL_EP_VUE_F AS (
    SELECT
        BRANCH_CODE AS CODE_AGENCE,
        FIELD_CHAR_2 AS CODE_CAF,
        CUSTOMER_ID AS MATRICULE_CLIENT,
        DR_PROD_AC AS NUMERO_COMPTE,
        PRIMARY_APPLICANT_NAME AS NOM_CLIENT,
        SUM(AMOUNT_FINANCED) AS CUM_MONTANT_FINANCE,
        SUM(ENCOURS_TOTAL_M) AS CUM_ENCOURS_CREDIT,
        SUM(OBJ_COL_EPV_VUE) AS OBJ_COL_EPV_VUE
    FROM OBJ_COL_EPV
    GROUP BY
        BRANCH_CODE,
        FIELD_CHAR_2,
        CUSTOMER_ID,
        DR_PROD_AC,
        PRIMARY_APPLICANT_NAME
),
GESTIONNAIRE_CAF AS (
    SELECT
        P.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        MAX(U.LOV_DESC) AS CHARGE_AFFAIRE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER P
    LEFT JOIN CFSFCUBS145.UDTM_LOV U
        ON U.FIELD_NAME = 'GESTION_PRET'
       AND U.LOV = P.FIELD_CHAR_2
    GROUP BY P.FIELD_CHAR_2
)
SELECT
    V.CODE_AGENCE,
    B.BRANCH_NAME,
    V.CODE_CAF,
    G.CHARGE_AFFAIRE,
    V.MATRICULE_CLIENT,
    V.NUMERO_COMPTE,
    V.NOM_CLIENT,
    V.CUM_MONTANT_FINANCE,
    V.CUM_ENCOURS_CREDIT,
    V.OBJ_COL_EPV_VUE
FROM OBJ_COL_EP_VUE_F V
LEFT JOIN GESTIONNAIRE_CAF G
    ON G.CODE_GESTION_PRET = V.CODE_CAF
LEFT JOIN CFSFCUBS145.STTM_BRANCH B
    ON B.BRANCH_CODE = V.CODE_AGENCE
ORDER BY
    V.CODE_AGENCE,
    V.CODE_CAF,
    V.MATRICULE_CLIENT
"""
