# Enrôlements PI / Mobile+ / USSD pour les nouveaux clients (comptes ouverts).
# Dates : début inclusif, fin exclusive.

PI_ENROLLEMENT_QUERY = """
WITH KYC AS (
    SELECT
        sc.CUSTOMER_NO,
        sc.LOCAL_BRANCH,
        b.BRANCH_NAME,
        cat.CUST_CAT_DESC AS CATEGORIE_COMPTE,
        p.CUSTOMER_PREFIX,
        DECODE(sc.CUSTOMER_TYPE, 'C', 'ENTREPRISE', 'I', 'PARTICULIER')
            || NVL(DECODE(p.SEX, 'M', 'HOMME', 'F', ' FEMME'), '') AS CATEGORIE,
        p.E_MAIL,
        p.MOBILE_NUMBER,
        sc.MAKER_ID,
        sc.CIF_CREATION_DATE AS DATE_CREATION
    FROM CFSFCUBS145.STTM_CUSTOMER sc
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b
        ON b.BRANCH_CODE = sc.LOCAL_BRANCH
    LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
        ON sc.CUSTOMER_NO = p.CUSTOMER_NO
    LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
        ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
),
udf_client_dc AS (
    SELECT
        sc.CUSTOMER_NO AS MATRICULE_CLIENT,
        udf.FIELD_VAL_13 AS CODE_GESTIONNAIRE_CLIENT,
        (
            SELECT lov2.LOV_DESC
            FROM CFSFCUBS145.UDTM_LOV lov2
            WHERE lov2.FIELD_NAME = 'GEST_CLIENT'
              AND lov2.LOV = udf.FIELD_VAL_13
        ) AS GESTIONNAIRE_CLIENT,
        udf.FIELD_VAL_15 AS CODE_APPORTEUR_AFFAIRE,
        (
            SELECT lov2.LOV_DESC
            FROM CFSFCUBS145.UDTM_LOV lov2
            WHERE lov2.FIELD_NAME = 'APP_AFFAIRE'
              AND lov2.LOV = udf.FIELD_VAL_15
        ) AS NOM_APPORTEUR_AFFAIRE
    FROM CFSFCUBS145.STTM_CUSTOMER sc
    LEFT JOIN CFSFCUBS145.CSTM_FUNCTION_USERDEF_FIELDS udf
        ON sc.CUSTOMER_NO = REPLACE(udf.REC_KEY, '~', '')
       AND udf.FUNCTION_ID = 'STDCIF'
    WHERE sc.CUSTOMER_NO NOT LIKE '000001'
),
base_client AS (
    SELECT
        k.LOCAL_BRANCH,
        k.BRANCH_NAME,
        c.CUST_NO,
        c.AC_DESC,
        c.AC_OPEN_DATE,
        k.MAKER_ID,
        k.DATE_CREATION,
        k.CATEGORIE_COMPTE,
        k.CUSTOMER_PREFIX,
        k.CATEGORIE,
        k.E_MAIL,
        k.MOBILE_NUMBER,
        u.CODE_GESTIONNAIRE_CLIENT,
        u.GESTIONNAIRE_CLIENT,
        u.CODE_APPORTEUR_AFFAIRE,
        u.NOM_APPORTEUR_AFFAIRE,
        ROW_NUMBER() OVER (
            PARTITION BY c.CUST_NO
            ORDER BY c.AC_OPEN_DATE DESC, c.CUST_AC_NO
        ) AS RN
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT c
    LEFT JOIN KYC k
        ON c.CUST_NO = k.CUSTOMER_NO
    LEFT JOIN udf_client_dc u
        ON u.MATRICULE_CLIENT = c.CUST_NO
    WHERE c.RECORD_STAT = 'O'
      AND c.AC_OPEN_DATE >= TO_DATE(:date_debut, 'YYYY-MM-DD')
      AND c.AC_OPEN_DATE < TO_DATE(:date_fin_exclusive, 'YYYY-MM-DD')
      AND NVL(c.MAKER_ID, 'X') != 'APIUSER1'
),
base_client_fn AS (
    SELECT *
    FROM base_client
    WHERE RN = 1
),
ABONNEMENT_OMMB AS (
    SELECT
        NUMEROCLIENT,
        MAX(DT_CRE_ENREG) AS DT_CRE_ENREG,
        MAX(DT_MAJ_ENREG) AS DT_MAJ_ENREG,
        MAX(DATEDERNIERECONNEXION) AS DATEDERNIERECONNEXION,
        MAX(ISENABLED) AS ISENABLED,
        'Enrôlé' AS STATUT_MOBILE_PLUS
    FROM OMB_SN.UTILISATEUR
    WHERE ISENABLED = '1'
    GROUP BY NUMEROCLIENT
),
PI AS (
    SELECT
        CUST_AC_NO,
        CUST_NO,
        STATUT_ENROLLEMENT_SPI,
        MAX(DT_CRE_ENREG) AS DT_CRE_ENREG,
        MAX(DT_MAJ_ENREG) AS DT_MAJ_ENREG,
        ISENABLED,
        TELEPHONECLIENT
    FROM (
        SELECT
            RE.CUST_AC_NO,
            RE.CUST_NO,
            PI.DT_CRE_ENREG,
            PI.DT_MAJ_ENREG,
            PI.ISENABLED,
            PI.TELEPHONECLIENT,
            CASE
                WHEN PI.NUMEROCOMPTE IS NOT NULL THEN 'Enrôlé'
                ELSE 'Non enrôlé'
            END AS STATUT_ENROLLEMENT_SPI
        FROM OMB_SN.PIENROLLEMENT PI
        LEFT JOIN CFSFCUBS145.STTM_CUST_ACCOUNT RE
            ON PI.NUMEROCOMPTE = RE.CUST_AC_NO
    )
    GROUP BY
        CUST_AC_NO,
        CUST_NO,
        STATUT_ENROLLEMENT_SPI,
        ISENABLED,
        TELEPHONECLIENT
),
USSDSUBSCRIPTION_orange AS (
    SELECT
        NUMCLIENT,
        BANKLNAME,
        ORANGEDOB,
        ISENABLED,
        'Enrôlé' AS STATUT_USSD,
        MAX(DT_CRE_ENREG) AS DT_CRE_ENREG,
        MAX(DT_MAJ_ENREG) AS DT_MAJ_ENREG
    FROM OMB_SN.USSDSUBSCRIPTION
    WHERE ISENABLED = '1'
    GROUP BY NUMCLIENT, BANKLNAME, ORANGEDOB, ISENABLED
)
SELECT
    c.LOCAL_BRANCH,
    c.BRANCH_NAME,
    c.CUST_NO,
    c.AC_DESC,
    c.AC_OPEN_DATE,
    c.DATE_CREATION,
    c.CATEGORIE_COMPTE,
    c.CUSTOMER_PREFIX,
    c.CATEGORIE,
    c.MOBILE_NUMBER,
    c.CODE_GESTIONNAIRE_CLIENT,
    c.GESTIONNAIRE_CLIENT,
    c.CODE_APPORTEUR_AFFAIRE,
    c.NOM_APPORTEUR_AFFAIRE,

    CASE
        WHEN O.STATUT_MOBILE_PLUS = 'Enrôlé' THEN 'Enrôlé'
        ELSE 'Non enrôlé'
    END AS STATUT_ENROLLEMENT_MOBILE_PLUS,
    O.DT_CRE_ENREG AS DT_CRE_ENREG_MOBILE_PLUS,
    O.DT_MAJ_ENREG AS DT_MAJ_ENREG_MOBILE_PLUS,
    CASE
        WHEN O.ISENABLED = 1 THEN 'Actif'
        ELSE 'Inactif'
    END AS STATUT_COFINA_MOBILE_PLUS,
    O.DATEDERNIERECONNEXION AS DERN_CONNEXION_MOBILE_PLUS,

    CASE
        WHEN I.STATUT_ENROLLEMENT_SPI = 'Enrôlé' THEN 'Enrôlé'
        ELSE 'Non enrôlé'
    END AS STATUT_ENROLLEMENT_SPI,
    I.DT_CRE_ENREG AS DT_CRE_ENREG_PI_SPI,
    I.DT_MAJ_ENREG AS DT_MAJ_ENREG_PI_SPI,
    CASE
        WHEN I.ISENABLED = 1 THEN 'Actif'
        ELSE 'Inactif'
    END AS STATUT_PI_SPI,
    I.TELEPHONECLIENT AS TELEPHONECLIENT_PI_SPI,

    CASE
        WHEN S.STATUT_USSD = 'Enrôlé' THEN 'Enrôlé'
        ELSE 'Non enrôlé'
    END AS STATUT_ENROLLEMENT_USSD,
    S.ORANGEDOB,
    S.DT_CRE_ENREG AS DT_CRE_ENREG_USSD,
    S.DT_MAJ_ENREG AS DT_MAJ_ENREG_USSD,
    CASE
        WHEN S.ISENABLED = 1 THEN 'Actif'
        ELSE 'Inactif'
    END AS STATUT_USSD
FROM base_client_fn c
LEFT JOIN ABONNEMENT_OMMB o
    ON c.CUST_NO = o.NUMEROCLIENT
LEFT JOIN PI i
    ON i.CUST_NO = c.CUST_NO
LEFT JOIN USSDSUBSCRIPTION_orange s
    ON s.NUMCLIENT = c.CUST_NO
"""
