# Requête PAR global live Flexcube (CFSFCUBS145).
# Date d'arrêté : :as_of_date (DD/MM/YYYY), bornée au jour courant pour le mois en cours.

PORTEFEUILLE_GLOBAL_QUERY = """
WITH NOMBRE_DOSSIER AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.BRANCH_CODE,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY p.FIELD_CHAR_2, p.BRANCH_CODE
),
NOMBRE_DOSSIER_IMP AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.BRANCH_CODE,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER_IMP
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND p.USER_DEFINED_STATUS NOT IN ('NORM', 'IMMO', 'DCL1')
    GROUP BY p.FIELD_CHAR_2, p.BRANCH_CODE
),
ENCOURS_RISQUE AS (
    SELECT
        ACCOUNT_NUMBER,
        CODE_GESTION_PRET,
        BRANCH_CODE,
        ENCOURS_TOTAL,
        ENCOURS_SAIN,
        ENCOURS_IMPAYE,
        DUREE_IMPAYE_A_DATE,
        CASE
            WHEN DUREE_IMPAYE_A_DATE > 0 THEN ENCOURS_TOTAL
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM (
        SELECT
            p.ACCOUNT_NUMBER,
            p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
            p.BRANCH_CODE,
            SUM(CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE >= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_SAIN,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE < TO_DATE(:as_of_date, 'DD/MM/YYYY')
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_IMPAYE,
            NVL(
                TO_DATE(:as_of_date, 'DD/MM/YYYY')
                - MIN(
                    CASE
                        WHEN CLS.SCHEDULE_DUE_DATE <= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                         AND (CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) > 0
                        THEN CLS.SCHEDULE_DUE_DATE
                    END
                ),
                0
            ) AS DUREE_IMPAYE_A_DATE
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
        JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p
            ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
        WHERE CLS.COMPONENT_NAME = 'PRINCIPAL'
          AND p.ACCOUNT_STATUS NOT IN ('L', 'V')
        GROUP BY
            p.FIELD_CHAR_2,
            p.BRANCH_CODE,
            p.ACCOUNT_NUMBER
    )
),
PAR_DETAIL_CAF AS (
    SELECT
        EC.CODE_GESTION_PRET,
        EC.BRANCH_CODE,
        SUM(EC.ENCOURS_TOTAL) AS ENCOURS_TOTAL,
        SUM(EC.ENCOURS_SAIN) AS ENCOURS_SAIN,
        SUM(EC.ENCOURS_IMPAYE) AS ENCOURS_IMPAYE,
        SUM(EC.ENCOURS_RISQUE) AS ENCOURS_RISQUE,
        MAX(NVL(ND.NOMBRE_DOSSIER, 0)) AS NOMBRE_DOSSIER,
        MAX(NVL(NDI.NOMBRE_DOSSIER_IMP, 0)) AS NOMBRE_DOSSIER_IMP,
        TRUNC(
            (SUM(EC.ENCOURS_IMPAYE) / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)) * 100,
            2
        ) AS RATIO_ENCOURS_IMPAYE,
        TRUNC(
            (
                MAX(NVL(NDI.NOMBRE_DOSSIER_IMP, 0))
                / NULLIF(MAX(NVL(ND.NOMBRE_DOSSIER, 0)), 0)
            ) * 100,
            2
        ) AS RATIO_NOMBRE_IMPAYE,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 0 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_0,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 30 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_30,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 90 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_90,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 180 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_180,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 360 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_360
    FROM ENCOURS_RISQUE EC
    LEFT JOIN NOMBRE_DOSSIER ND
        ON ND.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
       AND ND.BRANCH_CODE = EC.BRANCH_CODE
    LEFT JOIN NOMBRE_DOSSIER_IMP NDI
        ON NDI.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
       AND NDI.BRANCH_CODE = EC.BRANCH_CODE
    GROUP BY EC.CODE_GESTION_PRET, EC.BRANCH_CODE
),
DUREE_IMPAYE_A_DATE AS (
    SELECT
        p.ACCOUNT_NUMBER,
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        p.BRANCH_CODE,
        NVL(
            TO_DATE(:as_of_date, 'DD/MM/YYYY')
            - (
                SELECT MIN(TRUNC(z.SCHEDULE_DUE_DATE))
                FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
                WHERE z.ACCOUNT_NUMBER = p.ACCOUNT_NUMBER
                  AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
                  AND z.SCHEDULE_DUE_DATE <= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                  AND (z.AMOUNT_DUE - z.AMOUNT_SETTLED) > 0
            ),
            0
        ) AS DUREE_IMPAYE_A_DATE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
),
ENCOURS AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        c.BRANCH_CODE,
        c.PRIMARY_APPLICANT_NAME,
        SUM(z.AMOUNT_DUE - z.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
        SUM(
            CASE
                WHEN c.USER_DEFINED_STATUS IN ('NORM', 'IMPA')
                THEN (z.AMOUNT_DUE - z.AMOUNT_SETTLED)
                ELSE 0
            END
        ) AS ENCOURS_SAIN,
        SUM(
            CASE
                WHEN c.USER_DEFINED_STATUS NOT IN ('NORM', 'IMPA')
                THEN (z.AMOUNT_DUE - z.AMOUNT_SETTLED)
                ELSE 0
            END
        ) AS ENCOURS_IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME = 'PRINCIPAL'
    GROUP BY
        c.ACCOUNT_NUMBER,
        c.BRANCH_CODE,
        c.PRIMARY_APPLICANT_NAME
),
ENCOURS_RISQUE_PRET AS (
    SELECT
        d.CODE_GESTION_PRET,
        NVL(d.BRANCH_CODE, e.BRANCH_CODE) AS BRANCH_CODE,
        e.NO_PRET,
        e.PRIMARY_APPLICANT_NAME,
        e.ENCOURS_TOTAL,
        e.ENCOURS_SAIN,
        e.ENCOURS_IMPAYE,
        d.DUREE_IMPAYE_A_DATE,
        CASE
            WHEN d.DUREE_IMPAYE_A_DATE > 0 THEN e.ENCOURS_TOTAL
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM ENCOURS e
    LEFT JOIN DUREE_IMPAYE_A_DATE d
        ON e.NO_PRET = d.ACCOUNT_NUMBER
),
ENCOURS_RISQUE_PAR0 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR0
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 0
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR30 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR30
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 30
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR60 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR60
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 60
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR90 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR90
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 90
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR180 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR180
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 180
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR360 AS (
    SELECT
        CODE_GESTION_PRET,
        BRANCH_CODE,
        SUM(ENCOURS_RISQUE) AS ENCOURS_RISQUE_PAR360
    FROM ENCOURS_RISQUE_PRET
    WHERE DUREE_IMPAYE_A_DATE > 360
    GROUP BY CODE_GESTION_PRET, BRANCH_CODE
),
ENCOURS_RISQUE_PAR AS (
    SELECT
        P0.CODE_GESTION_PRET,
        P0.BRANCH_CODE,
        NVL(P0.ENCOURS_RISQUE_PAR0, 0) AS ENCOURS_RISQUE_PAR0,
        NVL(P30.ENCOURS_RISQUE_PAR30, 0) AS ENCOURS_RISQUE_PAR30,
        NVL(P60.ENCOURS_RISQUE_PAR60, 0) AS ENCOURS_RISQUE_PAR60,
        NVL(P90.ENCOURS_RISQUE_PAR90, 0) AS ENCOURS_RISQUE_PAR90,
        NVL(P180.ENCOURS_RISQUE_PAR180, 0) AS ENCOURS_RISQUE_PAR180,
        NVL(P360.ENCOURS_RISQUE_PAR360, 0) AS ENCOURS_RISQUE_PAR360
    FROM ENCOURS_RISQUE_PAR0 P0
    LEFT JOIN ENCOURS_RISQUE_PAR30 P30
        ON P0.CODE_GESTION_PRET = P30.CODE_GESTION_PRET
       AND P0.BRANCH_CODE = P30.BRANCH_CODE
    LEFT JOIN ENCOURS_RISQUE_PAR60 P60
        ON P0.CODE_GESTION_PRET = P60.CODE_GESTION_PRET
       AND P0.BRANCH_CODE = P60.BRANCH_CODE
    LEFT JOIN ENCOURS_RISQUE_PAR90 P90
        ON P0.CODE_GESTION_PRET = P90.CODE_GESTION_PRET
       AND P0.BRANCH_CODE = P90.BRANCH_CODE
    LEFT JOIN ENCOURS_RISQUE_PAR180 P180
        ON P0.CODE_GESTION_PRET = P180.CODE_GESTION_PRET
       AND P0.BRANCH_CODE = P180.BRANCH_CODE
    LEFT JOIN ENCOURS_RISQUE_PAR360 P360
        ON P0.CODE_GESTION_PRET = P360.CODE_GESTION_PRET
       AND P0.BRANCH_CODE = P360.BRANCH_CODE
),
GESTION_PRET AS (
    SELECT LOV, LOV_DESC
    FROM CFSFCUBS145.UDTM_LOV
    WHERE FIELD_NAME = 'GESTION_PRET'
)
SELECT
    gp.LOV_DESC AS CHARGE_AFFAIRE,
    BR.BRANCH_NAME,
    P.BRANCH_CODE,
    P.CODE_GESTION_PRET,
    NVL(P.NOMBRE_DOSSIER, 0) AS NOMBRE_DOSSIER,
    NVL(P.NOMBRE_DOSSIER_IMP, 0) AS NOMBRE_DOSSIER_IMP,
    NVL(P.ENCOURS_TOTAL, 0) AS ENCOURS_TOTAL,
    NVL(P.ENCOURS_SAIN, 0) AS ENCOURS_SAIN,
    NVL(P.ENCOURS_IMPAYE, 0) AS ENCOURS_IMPAYE,
    NVL(P.ENCOURS_RISQUE, 0) AS ENCOURS_RISQUE,
    NVL(P.RATIO_ENCOURS_IMPAYE, 0) AS RATIO_ENCOURS_IMPAYE,
    NVL(P.RATIO_NOMBRE_IMPAYE, 0) AS RATIO_NOMBRE_IMPAYE,
    NVL(P.PAR_0, 0) AS PAR_0,
    NVL(P.PAR_30, 0) AS PAR_30,
    NVL(P.PAR_90, 0) AS PAR_90,
    NVL(P.PAR_180, 0) AS PAR_180,
    NVL(P.PAR_360, 0) AS PAR_360,
    NVL(R.ENCOURS_RISQUE_PAR0, 0) AS ENCOURS_PAR_0,
    NVL(R.ENCOURS_RISQUE_PAR30, 0) AS ENCOURS_PAR_30,
    NVL(R.ENCOURS_RISQUE_PAR60, 0) AS ENCOURS_PAR_60,
    NVL(R.ENCOURS_RISQUE_PAR90, 0) AS ENCOURS_PAR_90,
    NVL(R.ENCOURS_RISQUE_PAR180, 0) AS ENCOURS_PAR_180,
    NVL(R.ENCOURS_RISQUE_PAR360, 0) AS ENCOURS_PAR_360
FROM PAR_DETAIL_CAF P
LEFT JOIN ENCOURS_RISQUE_PAR R
    ON R.CODE_GESTION_PRET = P.CODE_GESTION_PRET
   AND NVL(R.BRANCH_CODE, '-') = NVL(P.BRANCH_CODE, '-')
LEFT JOIN CFSFCUBS145.STTM_BRANCH BR
    ON BR.BRANCH_CODE = P.BRANCH_CODE
LEFT JOIN GESTION_PRET gp
    ON gp.LOV = P.CODE_GESTION_PRET
ORDER BY
    BR.BRANCH_NAME,
    P.CODE_GESTION_PRET
"""

# PAR AGENCE : même logique live, agrégée par BRANCH_CODE (pas par CAF).
PORTEFEUILLE_AGENCE_QUERY = """
WITH NOMBRE_DOSSIER AS (
    SELECT
        p.BRANCH_CODE,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY p.BRANCH_CODE
),
ENCOURS_RISQUE AS (
    SELECT
        ACCOUNT_NUMBER,
        BRANCH_CODE,
        ENCOURS_TOTAL,
        ENCOURS_SAIN,
        ENCOURS_IMPAYE,
        DUREE_IMPAYE_A_DATE,
        CASE
            WHEN DUREE_IMPAYE_A_DATE > 0 THEN ENCOURS_TOTAL
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM (
        SELECT
            p.ACCOUNT_NUMBER,
            p.BRANCH_CODE,
            SUM(CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE >= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_SAIN,
            SUM(
                CASE
                    WHEN CLS.SCHEDULE_DUE_DATE < TO_DATE(:as_of_date, 'DD/MM/YYYY')
                    THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED
                    ELSE 0
                END
            ) AS ENCOURS_IMPAYE,
            NVL(
                TO_DATE(:as_of_date, 'DD/MM/YYYY')
                - MIN(
                    CASE
                        WHEN CLS.SCHEDULE_DUE_DATE <= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                         AND (CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) > 0
                        THEN CLS.SCHEDULE_DUE_DATE
                    END
                ),
                0
            ) AS DUREE_IMPAYE_A_DATE
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
        JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p
            ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
        WHERE CLS.COMPONENT_NAME = 'PRINCIPAL'
          AND p.ACCOUNT_STATUS NOT IN ('L', 'V')
        GROUP BY
            p.BRANCH_CODE,
            p.ACCOUNT_NUMBER
    )
),
PAR_DETAIL_AGENCE AS (
    SELECT
        EC.BRANCH_CODE,
        SUM(EC.ENCOURS_TOTAL) AS ENCOURS_TOTAL,
        SUM(EC.ENCOURS_SAIN) AS ENCOURS_SAIN,
        SUM(EC.ENCOURS_IMPAYE) AS ENCOURS_IMPAYE,
        SUM(EC.ENCOURS_RISQUE) AS ENCOURS_RISQUE,
        MAX(NVL(ND.NOMBRE_DOSSIER, 0)) AS NOMBRE_DOSSIER,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 0 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_0,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 30 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_30,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 90 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_90,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 180 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_180,
        TRUNC(
            (
                SUM(CASE WHEN EC.DUREE_IMPAYE_A_DATE > 360 THEN EC.ENCOURS_RISQUE ELSE 0 END)
                / NULLIF(SUM(EC.ENCOURS_TOTAL), 0)
            ) * 100,
            2
        ) AS PAR_360
    FROM ENCOURS_RISQUE EC
    LEFT JOIN NOMBRE_DOSSIER ND
        ON ND.BRANCH_CODE = EC.BRANCH_CODE
    GROUP BY EC.BRANCH_CODE
),
DUREE_IMPAYE_A_DATE AS (
    SELECT
        p.ACCOUNT_NUMBER,
        p.BRANCH_CODE,
        NVL(
            TO_DATE(:as_of_date, 'DD/MM/YYYY')
            - (
                SELECT MIN(TRUNC(z.SCHEDULE_DUE_DATE))
                FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
                WHERE z.ACCOUNT_NUMBER = p.ACCOUNT_NUMBER
                  AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
                  AND z.SCHEDULE_DUE_DATE <= TO_DATE(:as_of_date, 'DD/MM/YYYY')
                  AND (z.AMOUNT_DUE - z.AMOUNT_SETTLED) > 0
            ),
            0
        ) AS DUREE_IMPAYE_A_DATE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
),
ENCOURS AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        c.BRANCH_CODE,
        SUM(z.AMOUNT_DUE - z.AMOUNT_SETTLED) AS ENCOURS_TOTAL
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME = 'PRINCIPAL'
    GROUP BY
        c.ACCOUNT_NUMBER,
        c.BRANCH_CODE
),
ENCOURS_RISQUE_PRET AS (
    SELECT
        NVL(d.BRANCH_CODE, e.BRANCH_CODE) AS BRANCH_CODE,
        e.NO_PRET,
        e.ENCOURS_TOTAL,
        d.DUREE_IMPAYE_A_DATE,
        CASE
            WHEN d.DUREE_IMPAYE_A_DATE > 0 THEN e.ENCOURS_TOTAL
            ELSE 0
        END AS ENCOURS_RISQUE
    FROM ENCOURS e
    LEFT JOIN DUREE_IMPAYE_A_DATE d
        ON e.NO_PRET = d.ACCOUNT_NUMBER
),
ENCOURS_RISQUE_PAR AS (
    SELECT
        BRANCH_CODE,
        SUM(CASE WHEN DUREE_IMPAYE_A_DATE > 0 THEN ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_RISQUE_PAR0,
        SUM(CASE WHEN DUREE_IMPAYE_A_DATE > 30 THEN ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_RISQUE_PAR30,
        SUM(CASE WHEN DUREE_IMPAYE_A_DATE > 90 THEN ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_RISQUE_PAR90,
        SUM(CASE WHEN DUREE_IMPAYE_A_DATE > 180 THEN ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_RISQUE_PAR180,
        SUM(CASE WHEN DUREE_IMPAYE_A_DATE > 360 THEN ENCOURS_RISQUE ELSE 0 END) AS ENCOURS_RISQUE_PAR360
    FROM ENCOURS_RISQUE_PRET
    GROUP BY BRANCH_CODE
),
PROVISIONS AS (
    SELECT
        p.BRANCH_CODE,
        SUM(
            NVL(e.ENCOURS_TOTAL, 0) * CASE
                WHEN p.USER_DEFINED_STATUS = 'DCL2' THEN 0.4
                WHEN p.USER_DEFINED_STATUS = 'DCL3' THEN 0.8
                WHEN p.USER_DEFINED_STATUS = 'DCL4' THEN 1
                ELSE 0
            END
        ) AS PROVISION_TOTAL
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    JOIN ENCOURS e
        ON e.NO_PRET = p.ACCOUNT_NUMBER
    WHERE p.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY p.BRANCH_CODE
)
SELECT
    BR.BRANCH_NAME,
    P.BRANCH_CODE,
    NVL(P.NOMBRE_DOSSIER, 0) AS NOMBRE_DOSSIER,
    NVL(P.ENCOURS_TOTAL, 0) AS ENCOURS_TOTAL,
    NVL(P.ENCOURS_SAIN, 0) AS ENCOURS_SAIN,
    NVL(P.ENCOURS_IMPAYE, 0) AS ENCOURS_IMPAYE,
    NVL(P.ENCOURS_RISQUE, 0) AS ENCOURS_RISQUE,
    NVL(P.PAR_0, 0) AS PAR_0,
    NVL(P.PAR_30, 0) AS PAR_30,
    NVL(P.PAR_90, 0) AS PAR_90,
    NVL(P.PAR_180, 0) AS PAR_180,
    NVL(P.PAR_360, 0) AS PAR_360,
    NVL(R.ENCOURS_RISQUE_PAR0, 0) AS ENCOURS_PAR_0,
    NVL(R.ENCOURS_RISQUE_PAR30, 0) AS ENCOURS_PAR_30,
    NVL(R.ENCOURS_RISQUE_PAR90, 0) AS ENCOURS_PAR_90,
    NVL(R.ENCOURS_RISQUE_PAR180, 0) AS ENCOURS_PAR_180,
    NVL(R.ENCOURS_RISQUE_PAR360, 0) AS ENCOURS_PAR_360,
    NVL(PR.PROVISION_TOTAL, 0) AS PROVISION_TOTAL
FROM PAR_DETAIL_AGENCE P
LEFT JOIN ENCOURS_RISQUE_PAR R
    ON NVL(R.BRANCH_CODE, '-') = NVL(P.BRANCH_CODE, '-')
LEFT JOIN PROVISIONS PR
    ON NVL(PR.BRANCH_CODE, '-') = NVL(P.BRANCH_CODE, '-')
LEFT JOIN CFSFCUBS145.STTM_BRANCH BR
    ON BR.BRANCH_CODE = P.BRANCH_CODE
ORDER BY
    BR.BRANCH_NAME
"""
