# Requête SQL Portefeuille global (une date de référence)
# Utiliser __DATE_REF__ comme placeholder pour la date (format DD/MM/YYYY)

PORTEFEUILLE_GLOBAL_QUERY = """
WITH NOMBRE_DOSSIER AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        COUNT(p.ACCOUNT_NUMBER) AS NOMBRE_DOSSIER
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER p
    GROUP BY p.FIELD_CHAR_2
),
ENCOURS_CAF AS (
    SELECT
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        SUM(CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED) AS ENCOURS_TOTAL,
        SUM(CASE WHEN CLS.SCHEDULE_DUE_DATE >= TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN CLS.AMOUNT_DUE ELSE 0 END) AS ENCOURS_SAIN,
        SUM(CASE WHEN CLS.SCHEDULE_DUE_DATE < TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED ELSE 0 END) AS ENCOURS_IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
    JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
    WHERE CLS.COMPONENT_NAME IN ('PRINCIPAL')
    GROUP BY p.FIELD_CHAR_2
),
ENCOURS_CODE_CAF AS (
    SELECT
        EC.CODE_GESTION_PRET,
        EC.ENCOURS_TOTAL,
        EC.ENCOURS_SAIN,
        EC.ENCOURS_IMPAYE,
        NVL(ND.NOMBRE_DOSSIER, 0) AS NOMBRE_DOSSIER,
        TRUNC((EC.ENCOURS_IMPAYE / NULLIF(EC.ENCOURS_TOTAL, 0)) * 100, 2) AS RATIO_ENCOURS_IMPAYE,
        TRUNC((NVL(ND.NOMBRE_DOSSIER, 0) / NULLIF(SUM(ND.NOMBRE_DOSSIER) OVER (), 0)) * 100, 2) AS RATIO_NOMBRE_IMPAYE
    FROM ENCOURS_CAF EC
    LEFT JOIN NOMBRE_DOSSIER ND ON ND.CODE_GESTION_PRET = EC.CODE_GESTION_PRET
    WHERE EC.ENCOURS_TOTAL <> 0
),
ECHEANCE_IMPY AS (
    SELECT
        CLS.ACCOUNT_NUMBER,
        p.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        (SELECT MAX(u.LOV_DESC) FROM CFSFCUBS145.UDTM_LOV u WHERE FIELD_NAME = 'GESTION_PRET' AND u.LOV = p.FIELD_CHAR_2) AS CHARGE_AFFAIRE,
        CLS.AMOUNT_DUE,
        CLS.AMOUNT_SETTLED,
        CLS.AMOUNT_DUE - CLS.AMOUNT_SETTLED AS PAR_CAPITAL_IMPY_ECH,
        CLS.SCHEDULE_DUE_DATE,
        TO_DATE('__DATE_REF__', 'DD/MM/YYYY') - TO_DATE(CLS.SCHEDULE_DUE_DATE) AS NB_JOUR_IMPY
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES CLS
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER p ON p.ACCOUNT_NUMBER = CLS.ACCOUNT_NUMBER
    WHERE CLS.COMPONENT_NAME IN ('PRINCIPAL') AND CLS.SCH_STATUS = 'IMPY'
),
SOLDE AS (
    SELECT
        ac_no,
        SUM(DECODE(drcr_ind, 'C', lcy_amount, 0)) - SUM(DECODE(drcr_ind, 'D', lcy_amount, 0)) AS SOLDE
    FROM CFSFCUBS145.acvw_all_ac_entries
    WHERE trn_dt <= TO_DATE('__DATE_REF__', 'DD/MM/YYYY') AND AC_NO LIKE '254%'
    GROUP BY ac_no
),
FINAL_CLTB_ACCOUNT_SCHEDULES AS (
    SELECT
        ACCOUNT_NUMBER,
        COMPONENT_NAME,
        CASE
            WHEN COMPONENT_NAME IN ('ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT') THEN SCHEDULE_ST_DATE
            ELSE SCHEDULE_DUE_DATE
        END AS SCHEDULE_DUE_DATE,
        SCH_STATUS,
        AMOUNT_DUE,
        AMOUNT_SETTLED
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
),
EXIGIBLE AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS EXIGIBLE
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN FINAL_CLTB_ACCOUNT_SCHEDULES z ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT')
      AND z.SCHEDULE_DUE_DATE <= TO_DATE('__DATE_REF__', 'DD/MM/YYYY')
    GROUP BY c.ACCOUNT_NUMBER
),
PAR_DETAIL AS (
    SELECT
        ACCOUNT_NUMBER,
        CHARGE_AFFAIRE,
        CODE_GESTION_PRET,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 0 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS PAR_0,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 30 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS PAR_30,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 90 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS PAR_90,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 180 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS PAR_180,
        SUM(CASE WHEN EY.NB_JOUR_IMPY > 360 THEN EY.PAR_CAPITAL_IMPY_ECH ELSE 0 END) AS PAR_360
    FROM ECHEANCE_IMPY EY
    GROUP BY ACCOUNT_NUMBER, CHARGE_AFFAIRE, CODE_GESTION_PRET
),
MAX_EY AS (
    SELECT ACCOUNT_NUMBER, MAX(EY.NB_JOUR_IMPY) AS MAX_NB_JOUR_IMPY
    FROM ECHEANCE_IMPY EY
    GROUP BY EY.ACCOUNT_NUMBER
),
ENCOURS AS (
    SELECT
        ACCOUNT_NUMBER,
        SUM(AMOUNT_DUE - AMOUNT_SETTLED) AS TOTAL,
        SUM(CASE WHEN SCHEDULE_DUE_DATE >= TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN AMOUNT_DUE - AMOUNT_SETTLED ELSE 0 END) AS SAIN,
        SUM(CASE WHEN SCHEDULE_DUE_DATE < TO_DATE('__DATE_REF__', 'DD/MM/YYYY') THEN AMOUNT_DUE - AMOUNT_SETTLED ELSE 0 END) AS IMPAYE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
    WHERE COMPONENT_NAME = 'PRINCIPAL'
    GROUP BY ACCOUNT_NUMBER
),
PROVISIONS_AGG AS (
    SELECT
        BR.BRANCH_NAME,
        C.FIELD_CHAR_2 AS CODE_GESTION_PRET,
        SUM(
            NVL(E.TOTAL, 0) * CASE
                WHEN C.USER_DEFINED_STATUS = 'DSL2' THEN 0.4
                WHEN C.USER_DEFINED_STATUS = 'DCL3' THEN 0.8
                WHEN C.USER_DEFINED_STATUS = 'DSCL4' THEN 1
                ELSE 1
            END
        ) AS PROVISION_TOTAL
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER C
    JOIN ENCOURS E ON E.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.STTM_BRANCH BR ON BR.BRANCH_CODE = C.BRANCH_CODE
    WHERE C.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY BR.BRANCH_NAME, C.FIELD_CHAR_2
),
RESULT_PAR_M AS (
    SELECT
        BR.BRANCH_CODE,
        BR.BRANCH_NAME,
        PD.CHARGE_AFFAIRE,
        PD.CODE_GESTION_PRET,
        PD.PAR_0,
        PD.PAR_30,
        PD.PAR_90,
        PD.PAR_180,
        PD.PAR_360
    FROM PAR_DETAIL PD
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER C ON PD.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.cltm_product_rth b ON C.PRODUCT_CODE = b.PRODUCT_CODE AND b.ACCOUNTING_ROLE = 'LOAN_ACCOUNT'
    LEFT JOIN CFSFCUBS145.GLVW_GLMASTER_E g ON b.ACCOUNT_HEAD = g.GL_CODE_E
    LEFT JOIN CFSFCUBS145.UDTM_LOV U1 ON U1.FIELD_NAME = 'GESTION_PRET' AND U1.LOV = c.FIELD_CHAR_2
    LEFT JOIN CFSFCUBS145.CSTM_FUNCTION_USERDEF_FIELDS UDF2 ON c.CUSTOMER_ID = SUBSTR(UDF2.REC_KEY, 1, 6) AND UDF2.FUNCTION_ID = 'STDCIF'
    LEFT JOIN CFSFCUBS145.UDTM_LOV U2 ON U2.FIELD_NAME = 'NAT_JURID' AND U2.LOV = UDF2.FIELD_VAL_13
    LEFT JOIN CFSFCUBS145.UDTM_LOV U3 ON U3.FIELD_NAME = 'SECTEUR_ACTIVITE' AND U3.LOV = c.FIELD_CHAR_4
    LEFT JOIN MAX_EY ME ON ME.ACCOUNT_NUMBER = PD.ACCOUNT_NUMBER
    LEFT JOIN ENCOURS E ON E.ACCOUNT_NUMBER = PD.ACCOUNT_NUMBER
    LEFT JOIN SOLDE bal ON c.FIELD_NUMBER_2 = bal.ac_no
    LEFT JOIN EXIGIBLE Z ON Z.NO_PRET = C.ACCOUNT_NUMBER
    LEFT JOIN CFSFCUBS145.STTM_BRANCH BR ON BR.BRANCH_CODE = C.BRANCH_CODE
    WHERE c.PRODUCT_CODE NOT LIKE 'RA%'
),
PAR_M AS (
    SELECT
        RPM.BRANCH_NAME,
        RPM.CODE_GESTION_PRET,
        RPM.CHARGE_AFFAIRE,
        SUM(RPM.PAR_0) AS PAR_0,
        SUM(RPM.PAR_30) AS PAR_30,
        SUM(RPM.PAR_90) AS PAR_90,
        SUM(RPM.PAR_180) AS PAR_180,
        SUM(RPM.PAR_360) AS PAR_360
    FROM RESULT_PAR_M RPM
    GROUP BY RPM.BRANCH_NAME, RPM.CODE_GESTION_PRET, RPM.CHARGE_AFFAIRE
)
SELECT
    PM.CHARGE_AFFAIRE,
    PM.BRANCH_NAME,
    PM.CODE_GESTION_PRET,
    ENC.ENCOURS_TOTAL,
    ENC.ENCOURS_IMPAYE,
    ENC.NOMBRE_DOSSIER,
    ENC.RATIO_ENCOURS_IMPAYE,
    ENC.RATIO_NOMBRE_IMPAYE,
    NVL(PA.PROVISION_TOTAL, 0) AS PROVISION_TOTAL,
    PM.PAR_0 AS ENCOURS_PAR_0,
    TRUNC((PM.PAR_0 / ENC.ENCOURS_TOTAL) * 100, 2) AS PAR_0,
    PM.PAR_30 AS ENCOURS_PAR_30,
    TRUNC((PM.PAR_30 / ENC.ENCOURS_TOTAL) * 100, 2) AS PAR_30,
    PM.PAR_90 AS ENCOURS_PAR_90,
    TRUNC((PM.PAR_90 / ENC.ENCOURS_TOTAL) * 100, 2) AS PAR_90,
    PM.PAR_180 AS ENCOURS_PAR_180,
    TRUNC((PM.PAR_180 / ENC.ENCOURS_TOTAL) * 100, 2) AS PAR_180,
    PM.PAR_360 AS ENCOURS_PAR_360,
    TRUNC((PM.PAR_360 / ENC.ENCOURS_TOTAL) * 100, 2) AS PAR_360
FROM PAR_M PM
JOIN ENCOURS_CODE_CAF ENC ON ENC.CODE_GESTION_PRET = PM.CODE_GESTION_PRET
LEFT JOIN PROVISIONS_AGG PA ON PA.BRANCH_NAME = PM.BRANCH_NAME AND PA.CODE_GESTION_PRET = PM.CODE_GESTION_PRET
"""


def get_query_for_date(date_str: str) -> str:
    """Retourne la requête Portefeuille global avec la date de référence (DD/MM/YYYY)."""
    return PORTEFEUILLE_GLOBAL_QUERY.replace("__DATE_REF__", date_str)
