# Requête SQL Portefeuille global : table DASH_PAR_GLOBAL (snapshot Cofina)
# Filtre : MAX(MIGRATION_DATE_MINUS1) dans le mois calendaire (MM/YYYY), comme DASH_DEPOT_GARANTIE.
# Important : les lots DASH n’ont souvent pas le dernier jour du mois (ex. 02/04/2026 au lieu de 30/04/2026) ;
# un filtre sur une date exacte renvoie 0 ligne et l’onglet PAR | CAF reste vide.

PORTEFEUILLE_GLOBAL_QUERY = """
SELECT
    CHARGE_AFFAIRE,
    BRANCH_NAME,
    CODE_GESTION_PRET,
    ENCOURS_TOTAL,
    ENCOURS_IMPAYE,
    NOMBRE_DOSSIER,
    RATIO_ENCOURS_IMPAYE,
    RATIO_NOMBRE_IMPAYE,
    PROVISION_TOTAL,
    ENCOURS_PAR_0,
    PAR_0,
    ENCOURS_PAR_30,
    PAR_30,
    ENCOURS_PAR_90,
    PAR_90,
    ENCOURS_PAR_180,
    PAR_180,
    ENCOURS_PAR_360,
    PAR_360,
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_PAR_GLOBAL
WHERE MIGRATION_DATE_MINUS1 = (
    SELECT MAX(d.MIGRATION_DATE_MINUS1)
    FROM DASH_PAR_GLOBAL d
    WHERE TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') = :month_year
)
ORDER BY BRANCH_NAME, CODE_GESTION_PRET, CHARGE_AFFAIRE
"""
