# Tables DASH Ria (Cofina) — même snapshot que OM / Wave.


def sql_dash_envoi_ria(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_ENVOIE_RIA_M_1,
    VOLUME_ENVOIE_RIA_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_ENVOIE_RIA
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_ENVOIE_RIA d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""


def sql_dash_paiement_ria(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_PAIEMENT_RIA_M_1,
    VOLUME_PAIEMENT_RIA_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_PAIEMENT_RIA
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_PAIEMENT_RIA d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""
