"""
Requêtes Vue 360 mobile — Flexcube CFSFCUBS145.
"""

# Agrégats crédit / épargne — une passe Oracle (évite 5 sous-requêtes par ligne).
_CLIENT_AGG_CTES = """
CREDIT_STATS AS (
    SELECT
        c.CUSTOMER_ID,
        COUNT(DISTINCT c.ACCOUNT_NUMBER) AS ACTIVE_CREDITS_COUNT,
        NVL(SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)), 0) AS TOTAL_OUTSTANDING,
        NVL(MAX(
            CASE
                WHEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
                     AND z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                THEN GREATEST(0, TRUNC(SYSDATE) - TRUNC(z.SCHEDULE_DUE_DATE))
                ELSE 0
            END
        ), 0) AS PAR_DAYS
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
      ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME = 'PRINCIPAL'
      {credit_customer_filter}
    GROUP BY c.CUSTOMER_ID
),
SAVINGS_STATS AS (
    SELECT
        ca.CUST_NO AS CUSTOMER_NO,
        NVL(SUM(bal.CURRENT_BALANCE), 0) AS SAVINGS_BALANCE
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
    JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS ac ON ac.ACCOUNT_CLASS = ca.ACCOUNT_CLASS
    JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON bal.CUST_AC_NO = ca.CUST_AC_NO
    WHERE ac.ACCOUNT_CODE = '253'
      AND ca.RECORD_STAT = 'O'
      {savings_customer_filter}
    GROUP BY ca.CUST_NO
),
FIRST_ACCOUNT AS (
    SELECT CUST_NO AS CUSTOMER_NO, MIN(CUST_AC_NO) AS ACCOUNT_NUMBER
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT
    WHERE RECORD_STAT = 'O'
      {account_customer_filter}
    GROUP BY CUST_NO
)
"""

CLIENTS_LIST_SELECT = """
SELECT
    sc.CUSTOMER_NO,
    sc.CUSTOMER_NO AS SC_CUSTOMER_NO,
    sc.FULL_NAME,
    p.FIRST_NAME,
    NVL(p.MIDDLE_NAME, sc.FULL_NAME) AS LAST_NAME,
    sc.EXT_REF_NO AS MATRICULE,
    fa.ACCOUNT_NUMBER,
    NVL(p.MOBILE_NUMBER, p.TELEPHONE) AS PHONE,
    cat.CUST_CAT_DESC AS SEGMENT,
    DECODE(sc.RECORD_STAT, 'O', 'active', 'C', 'inactive', 'inactive') AS STATUS,
    b.BRANCH_NAME AS AGENCY,
    sc.LOCAL_BRANCH AS BRANCH_CODE,
    NVL(cs.TOTAL_OUTSTANDING, 0) AS TOTAL_OUTSTANDING,
    NVL(ss.SAVINGS_BALANCE, 0) AS SAVINGS_BALANCE,
    NVL(cs.ACTIVE_CREDITS_COUNT, 0) AS ACTIVE_CREDITS_COUNT,
    NVL(cs.PAR_DAYS, 0) AS PAR_DAYS
FROM CFSFCUBS145.STTM_CUSTOMER sc
LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
    ON sc.CUSTOMER_NO = p.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
    ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
LEFT JOIN CFSFCUBS145.STTM_BRANCH b
    ON b.BRANCH_CODE = sc.LOCAL_BRANCH
LEFT JOIN CREDIT_STATS cs ON cs.CUSTOMER_ID = sc.CUSTOMER_NO
LEFT JOIN SAVINGS_STATS ss ON ss.CUSTOMER_NO = sc.CUSTOMER_NO
LEFT JOIN FIRST_ACCOUNT fa ON fa.CUSTOMER_NO = sc.CUSTOMER_NO
"""

# Détail client (1 ligne) — sous-requêtes acceptables.
CLIENTS_BASE_SELECT = """
SELECT
    sc.CUSTOMER_NO,
    sc.FULL_NAME,
    p.FIRST_NAME,
    NVL(p.MIDDLE_NAME, sc.FULL_NAME) AS LAST_NAME,
    sc.EXT_REF_NO AS MATRICULE,
    (
        SELECT MIN(ca.CUST_AC_NO)
        FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
        WHERE ca.CUST_NO = sc.CUSTOMER_NO
          AND ca.RECORD_STAT = 'O'
          AND ROWNUM = 1
    ) AS ACCOUNT_NUMBER,
    NVL(p.MOBILE_NUMBER, p.TELEPHONE) AS PHONE,
    cat.CUST_CAT_DESC AS SEGMENT,
    DECODE(sc.RECORD_STAT, 'O', 'active', 'C', 'inactive', 'inactive') AS STATUS,
    b.BRANCH_NAME AS AGENCY,
    sc.LOCAL_BRANCH AS BRANCH_CODE,
    NVL((
        SELECT SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0))
        FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
        JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
          ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
        WHERE c.CUSTOMER_ID = sc.CUSTOMER_NO
          AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
          AND z.COMPONENT_NAME = 'PRINCIPAL'
    ), 0) AS TOTAL_OUTSTANDING,
    NVL((
        SELECT SUM(bal.CURRENT_BALANCE)
        FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
        JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS ac ON ac.ACCOUNT_CLASS = ca.ACCOUNT_CLASS
        JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON bal.CUST_AC_NO = ca.CUST_AC_NO
        WHERE ca.CUST_NO = sc.CUSTOMER_NO
          AND ac.ACCOUNT_CODE = '253'
          AND ca.RECORD_STAT = 'O'
    ), 0) AS SAVINGS_BALANCE,
    NVL((
        SELECT COUNT(*)
        FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
        WHERE c.CUSTOMER_ID = sc.CUSTOMER_NO
          AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
    ), 0) AS ACTIVE_CREDITS_COUNT,
    NVL((
        SELECT MAX(
            GREATEST(0, TRUNC(SYSDATE) - TRUNC(z.SCHEDULE_DUE_DATE))
        )
        FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
        JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
          ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
        WHERE c.CUSTOMER_ID = sc.CUSTOMER_NO
          AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
          AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT')
          AND NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
          AND z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
    ), 0) AS PAR_DAYS
FROM CFSFCUBS145.STTM_CUSTOMER sc
LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
    ON sc.CUSTOMER_NO = p.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
    ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
LEFT JOIN CFSFCUBS145.STTM_BRANCH b
    ON b.BRANCH_CODE = sc.LOCAL_BRANCH
"""

CLIENTS_BY_BRANCHES = (
    "WITH BRANCH_CUSTOMERS AS ("
    + """
    SELECT sc.CUSTOMER_NO
    FROM CFSFCUBS145.STTM_CUSTOMER sc
    WHERE sc.RECORD_STAT IN ('O', 'C')
      AND sc.LOCAL_BRANCH IN ({branch_placeholders})
), """
    + _CLIENT_AGG_CTES.format(
        credit_customer_filter="AND c.CUSTOMER_ID IN (SELECT CUSTOMER_NO FROM BRANCH_CUSTOMERS)",
        savings_customer_filter="AND ca.CUST_NO IN (SELECT CUSTOMER_NO FROM BRANCH_CUSTOMERS)",
        account_customer_filter="AND CUST_NO IN (SELECT CUSTOMER_NO FROM BRANCH_CUSTOMERS)",
    )
    + CLIENTS_LIST_SELECT
    + """
WHERE sc.CUSTOMER_NO IN (SELECT CUSTOMER_NO FROM BRANCH_CUSTOMERS)
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
"""
)

# Recherche rapide — KPI financiers chargés sur la fiche client (GET /clients/{id}).
CLIENTS_SEARCH_LIGHT_SELECT = """
SELECT
    sc.CUSTOMER_NO,
    sc.FULL_NAME,
    p.FIRST_NAME,
    NVL(p.MIDDLE_NAME, sc.FULL_NAME) AS LAST_NAME,
    sc.EXT_REF_NO AS MATRICULE,
    (
        SELECT MIN(ca.CUST_AC_NO)
        FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
        WHERE ca.CUST_NO = sc.CUSTOMER_NO
          AND ca.RECORD_STAT = 'O'
          AND ROWNUM = 1
    ) AS ACCOUNT_NUMBER,
    NVL(p.MOBILE_NUMBER, p.TELEPHONE) AS PHONE,
    NVL(cat.CUST_CAT_DESC, 'Standard') AS SEGMENT,
    DECODE(sc.RECORD_STAT, 'O', 'active', 'C', 'inactive', 'inactive') AS STATUS,
    b.BRANCH_NAME AS AGENCY,
    sc.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CFSFCUBS145.STTM_CUSTOMER sc
LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
    ON sc.CUSTOMER_NO = p.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
    ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
LEFT JOIN CFSFCUBS145.STTM_BRANCH b
    ON b.BRANCH_CODE = sc.LOCAL_BRANCH
"""

CLIENTS_SEARCH = {
    "matricule": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND UPPER(sc.EXT_REF_NO) LIKE UPPER(:query)
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
    "account_number": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND EXISTS (
      SELECT 1 FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
      WHERE ca.CUST_NO = sc.CUSTOMER_NO
        AND ca.CUST_AC_NO LIKE :query
  )
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
    "first_name": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND UPPER(p.FIRST_NAME) LIKE UPPER(:query)
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
    "last_name": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND (
      UPPER(p.MIDDLE_NAME) LIKE UPPER(:query)
      OR UPPER(sc.FULL_NAME) LIKE UPPER(:query)
  )
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
    "phone": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND (
      p.MOBILE_NUMBER LIKE :query
      OR p.TELEPHONE LIKE :query
  )
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
    "customer_id": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND sc.CUSTOMER_NO LIKE :query
  {branch_filter}
ORDER BY sc.CUSTOMER_NO
FETCH FIRST :limit ROWS ONLY
""",
    "name": CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND UPPER(sc.FULL_NAME) LIKE UPPER(:query)
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
""",
}

# Recherche client unifiée — nom, matricule, n° compte ou téléphone mobile.
CLIENTS_SEARCH_FLEX = """
WITH CLIENT AS (
    SELECT
        c.CUSTOMER_NO,
        c.CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        CAST(NULL AS VARCHAR2(50)) AS ACCOUNT_NUMBER,
        CAST(NULL AS VARCHAR2(30)) AS PHONE
    FROM CFSFCUBS145.STTM_CUSTOMER c
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.LOCAL_BRANCH
    WHERE ({customer_name_filter})
      {branch_filter_customer}
    UNION
    SELECT
        c.CUSTOMER_NO,
        c.CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        CAST(NULL AS VARCHAR2(50)) AS ACCOUNT_NUMBER,
        CAST(NULL AS VARCHAR2(30)) AS PHONE
    FROM CFSFCUBS145.STTM_CUSTOMER c
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.LOCAL_BRANCH
    WHERE c.CUSTOMER_NO LIKE :query_prefix
      {branch_filter_customer}
    UNION
    SELECT
        a.CUST_NO AS CUSTOMER_NO,
        a.AC_DESC AS CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        a.CUST_AC_NO AS ACCOUNT_NUMBER,
        CAST(NULL AS VARCHAR2(30)) AS PHONE
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT a
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = a.BRANCH_CODE
    WHERE a.CUST_AC_NO LIKE :query_prefix
      {branch_filter_account}
    {phone_union}
    {id_union}
)
SELECT
    e.CUSTOMER_NO,
    e.CUSTOMER_NAME1 AS FULL_NAME,
    e.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    NVL(sc.EXT_REF_NO, e.CUSTOMER_NO) AS MATRICULE,
    e.ACCOUNT_NUMBER,
    NVL(e.PHONE, NVL(p.MOBILE_NUMBER, p.TELEPHONE)) AS PHONE,
    NVL(cat.CUST_CAT_DESC, 'Standard') AS SEGMENT,
    DECODE(sc.RECORD_STAT, 'O', 'active', 'C', 'inactive', 'inactive') AS STATUS,
    e.BRANCH_NAME AS AGENCY,
    e.BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    NVL(cr.ACTIVE_CREDITS_COUNT, 0) AS ACTIVE_CREDITS_COUNT,
    NVL(ac.ACCOUNTS_COUNT, 0) AS ACCOUNTS_COUNT,
    NVL(cr.CREDITS_COUNT, 0) AS CREDITS_COUNT,
    0 AS PAR_DAYS,
    sc.CUSTOMER_NO AS SC_CUSTOMER_NO
FROM CLIENT e
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER sc ON e.CUSTOMER_NO = sc.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p ON p.CUSTOMER_NO = e.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
LEFT JOIN (
    SELECT CUST_NO AS CUSTOMER_NO, COUNT(*) AS ACCOUNTS_COUNT
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT
    WHERE RECORD_STAT = 'O'
    GROUP BY CUST_NO
) ac ON ac.CUSTOMER_NO = e.CUSTOMER_NO
LEFT JOIN (
    SELECT
        CUSTOMER_ID AS CUSTOMER_NO,
        COUNT(*) AS CREDITS_COUNT,
        SUM(CASE WHEN ACCOUNT_STATUS NOT IN ('L', 'V') THEN 1 ELSE 0 END) AS ACTIVE_CREDITS_COUNT
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER
    GROUP BY CUSTOMER_ID
) cr ON cr.CUSTOMER_NO = e.CUSTOMER_NO
WHERE sc.CUSTOMER_CATEGORY != '000'
ORDER BY e.CUSTOMER_NAME1
FETCH FIRST :limit ROWS ONLY
"""

CLIENTS_SEARCH_FLEX_PHONE_UNION = """
    UNION
    SELECT
        p.CUSTOMER_NO,
        c.CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        CAST(NULL AS VARCHAR2(50)) AS ACCOUNT_NUMBER,
        p.MOBILE_NUMBER AS PHONE
    FROM CFSFCUBS145.STTM_CUST_PERSONAL p
    LEFT JOIN CFSFCUBS145.STTM_CUSTOMER c ON c.CUSTOMER_NO = p.CUSTOMER_NO
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.LOCAL_BRANCH
    WHERE (
        p.MOBILE_NUMBER LIKE :query_prefix
        OR p.TELEPHONE LIKE :query_prefix
    )
      {branch_filter_customer}
"""

# Recherche pièce d'identité — CNI (P_NATIONAL_ID), passeport, UNIQUE_ID (autre type).
CLIENTS_SEARCH_FLEX_ID_UNION = """
    UNION
    SELECT
        p.CUSTOMER_NO,
        c.CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        CAST(NULL AS VARCHAR2(50)) AS ACCOUNT_NUMBER,
        CAST(NULL AS VARCHAR2(30)) AS PHONE
    FROM CFSFCUBS145.STTM_CUST_PERSONAL p
    LEFT JOIN CFSFCUBS145.STTM_CUSTOMER c ON c.CUSTOMER_NO = p.CUSTOMER_NO
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.LOCAL_BRANCH
    WHERE (
        UPPER(REPLACE(REPLACE(REPLACE(REPLACE(NVL(p.P_NATIONAL_ID, ''), ' ', ''), '-', ''), '.', ''), '/', ''))
            LIKE UPPER(:query_id)
        OR UPPER(REPLACE(REPLACE(REPLACE(REPLACE(NVL(p.PASSPORT_NO, ''), ' ', ''), '-', ''), '.', ''), '/', ''))
            LIKE UPPER(:query_id)
    )
      {branch_filter_customer}
    UNION
    SELECT
        c.CUSTOMER_NO,
        c.CUSTOMER_NAME1,
        b.BRANCH_CODE,
        b.BRANCH_NAME,
        CAST(NULL AS VARCHAR2(50)) AS ACCOUNT_NUMBER,
        CAST(NULL AS VARCHAR2(30)) AS PHONE
    FROM CFSFCUBS145.STTM_CUSTOMER c
    LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.LOCAL_BRANCH
    WHERE UPPER(REPLACE(REPLACE(REPLACE(REPLACE(NVL(c.UNIQUE_ID_VALUE, ''), ' ', ''), '-', ''), '.', ''), '/', ''))
            LIKE UPPER(:query_id)
      {branch_filter_customer}
"""

# Recherche compte — index Flexcube sur CUST_AC_NO (évite scan CUSTOMERS DASH 45M lignes).
_CLIENT_ACCOUNT_FLEX_SELECT = """
SELECT
    sc.CUSTOMER_NO,
    sc.FULL_NAME,
    p.FIRST_NAME,
    NVL(p.MIDDLE_NAME, sc.FULL_NAME) AS LAST_NAME,
    sc.EXT_REF_NO AS MATRICULE,
    ca.CUST_AC_NO AS ACCOUNT_NUMBER,
    NVL(p.MOBILE_NUMBER, p.TELEPHONE) AS PHONE,
    NVL(cat.CUST_CAT_DESC, 'Standard') AS SEGMENT,
    DECODE(sc.RECORD_STAT, 'O', 'active', 'C', 'inactive', 'inactive') AS STATUS,
    b.BRANCH_NAME AS AGENCY,
    sc.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
JOIN CFSFCUBS145.STTM_CUSTOMER sc ON sc.CUSTOMER_NO = ca.CUST_NO
LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p ON sc.CUSTOMER_NO = p.CUSTOMER_NO
LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY
LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = sc.LOCAL_BRANCH
"""

CLIENTS_SEARCH_ACCOUNT_EXACT_FLEX = (
    _CLIENT_ACCOUNT_FLEX_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND ca.CUST_AC_NO = :account
  {branch_filter}
ORDER BY sc.FULL_NAME
FETCH FIRST :limit ROWS ONLY
"""
)

CLIENTS_SEARCH_ACCOUNT_PREFIX_FLEX = (
    _CLIENT_ACCOUNT_FLEX_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND ca.CUST_AC_NO LIKE :account_prefix
  {branch_filter}
ORDER BY ca.CUST_AC_NO
FETCH FIRST :limit ROWS ONLY
"""
)

CUSTOMER_BY_ACCOUNT_FLEX = (
    _CLIENT_ACCOUNT_FLEX_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND ca.CUST_AC_NO = :account
  {branch_filter}
FETCH FIRST 1 ROWS ONLY
"""
)

CUSTOMER_BY_ID_LIGHT_FLEX = (
    CLIENTS_SEARCH_LIGHT_SELECT
    + """
WHERE sc.RECORD_STAT IN ('O', 'C')
  AND sc.CUSTOMER_NO = :customer_no
  {branch_filter}
FETCH FIRST 1 ROWS ONLY
"""
)

CLIENT_BY_ID = CLIENTS_BASE_SELECT + """
WHERE sc.CUSTOMER_NO = :customer_no
  {branch_filter}
FETCH FIRST 1 ROWS ONLY
"""

_CREDIT_PRODUCTION_CTES = """
DEBLOCAGE_RAW AS (
    SELECT
        account_number,
        COALESCE(DTYPE, 'VIDE') AS DTYPE,
        MAX(SCHEDULE_LINKAGE) AS SCHEDULE_LINKAGE
    FROM CFSFCUBS145.CLTB_DISBR_SCHEDULES
    WHERE (DTYPE <> 'X') OR DTYPE IS NULL
    GROUP BY account_number, COALESCE(DTYPE, 'VIDE')
),
DEBLOCAGE AS (
    SELECT
        account_number,
        MAX(SCHEDULE_LINKAGE) AS SCHEDULE_LINKAGE
    FROM DEBLOCAGE_RAW
    GROUP BY account_number
),
ECRITURE_DEBLOCAGE AS (
    SELECT
        e.RELATED_ACCOUNT,
        MAX(e.TRN_DT) AS TRN_DT
    FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES e
    WHERE e.TRN_CODE = '040'
      AND e.MODULE = 'CL'
      AND e.EVENT = 'DSBR'
      AND e.AC_NO LIKE '251%'
    GROUP BY e.RELATED_ACCOUNT
),
ENCOURS_COFINA AS (
    SELECT
        ACCOUNT_NUMBER,
        SUM(AMOUNT_DUE) AS MONTANT_DU,
        SUM(AMOUNT_DUE - AMOUNT_SETTLED) AS ENCOURS_TOTAL,
        SUM(
            CASE
                WHEN SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
                THEN AMOUNT_DUE
                ELSE 0
            END
        ) AS ENCOURS_SAIN,
        SUM(
            CASE
                WHEN SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                THEN AMOUNT_DUE - AMOUNT_SETTLED
                ELSE 0
            END
        ) AS ENCOURS_IMPAYE,
        ROUND(
            CASE
                WHEN SUM(AMOUNT_DUE) = 0 THEN 0
                ELSE (SUM(AMOUNT_SETTLED) / SUM(AMOUNT_DUE)) * 100
            END,
            2
        ) AS POURCENTAGE_REMBOURSEMENT
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
    WHERE COMPONENT_NAME = 'PRINCIPAL'
    GROUP BY ACCOUNT_NUMBER
),
"""

_CREDIT_SCHEDULE_CTE = """
SCHEDULE_AGG AS (
    SELECT
        z.ACCOUNT_NUMBER,
        SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS TOTAL_OUTSTANDING,
        SUM(CASE WHEN z.COMPONENT_NAME = 'PRINCIPAL'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS PRINCIPAL_OUTSTANDING,
        SUM(CASE WHEN z.COMPONENT_NAME = 'MAIN_INT'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS INTEREST_OUTSTANDING,
        SUM(CASE WHEN z.COMPONENT_NAME LIKE '%PNTY%'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS PENALTIES_OUTSTANDING,
        SUM(CASE WHEN UPPER(z.COMPONENT_NAME) LIKE '%FTC%'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS FTC_OUTSTANDING,
        SUM(CASE WHEN UPPER(z.COMPONENT_NAME) LIKE '%ACS%'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS ACS_OUTSTANDING,
        SUM(CASE
            WHEN UPPER(z.COMPONENT_NAME) LIKE '%OPEN%'
                 OR UPPER(z.COMPONENT_NAME) LIKE '%OUV%'
                 OR UPPER(z.COMPONENT_NAME) LIKE '%DOS%'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS OPENING_FEE_OUTSTANDING,
        SUM(CASE
            WHEN UPPER(z.COMPONENT_NAME) LIKE '%COFI%'
                 OR UPPER(z.COMPONENT_NAME) LIKE '%CARTE%'
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS COFICARTE_FEE_OUTSTANDING,
        SUM(CASE WHEN z.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS DUE_AMOUNT,
        SUM(CASE
            WHEN z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                 AND NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
            THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END) AS OVERDUE_AMOUNT,
        MAX(CASE
            WHEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
                 AND z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
            THEN GREATEST(0, TRUNC(SYSDATE) - TRUNC(z.SCHEDULE_DUE_DATE)) ELSE 0 END) AS PAR_DAYS,
        MIN(CASE
            WHEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
                 AND z.SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
            THEN z.SCHEDULE_DUE_DATE END) AS NEXT_DUE_DATE
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
    GROUP BY z.ACCOUNT_NUMBER
)
"""

_CREDIT_SELECT_BODY = """
    c.BRANCH_CODE AS CODE_AGENCE,
    b.BRANCH_NAME AS NOM_AGENCE,
    c.ACCOUNT_NUMBER AS LOAN_NUMBER,
    c.ACCOUNT_NUMBER AS NO_PRET,
    c.CUSTOMER_ID AS CLIENT_ID,
    c.CUSTOMER_ID AS MATRICULE_CLIENT,
    NVL(c.PRIMARY_APPLICANT_NAME, sc.FULL_NAME) AS CLIENT_NAME,
    NVL(c.PRIMARY_APPLICANT_NAME, sc.FULL_NAME) AS NOM_CLIENT,
    TO_CHAR(c.DR_PROD_AC) AS COMPTE,
    (
        SELECT g.GL_DESC_E
        FROM CFSFCUBS145.CLTM_PRODUCT_RTH pr
        JOIN CFSFCUBS145.GLVW_GLMASTER_E g ON pr.ACCOUNT_HEAD = g.GL_CODE_E
        WHERE pr.PRODUCT_CODE = c.PRODUCT_CODE
          AND pr.ACCOUNTING_ROLE = 'LOAN_ACCOUNT'
          AND ROWNUM = 1
    ) AS TYPE_PRET,
    TO_CHAR(c.BOOK_DATE, 'YYYY-MM-DD') AS DATE_MISE_EN_PLACE,
    TO_CHAR(d.SCHEDULE_LINKAGE, 'YYYY-MM-DD') AS DATE_VAL_MISE_EN_PLACE,
    TO_CHAR(ed.TRN_DT, 'YYYY-MM-DD') AS DATE_DEBLOCAGE,
    TO_CHAR(c.MATURITY_DATE, 'YYYY-MM-DD') AS DATE_MATURITE,
    (
        SELECT TO_CHAR(MIN(sc.schedule_due_date), 'YYYY-MM-DD')
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES sc
        WHERE sc.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
          AND sc.COMPONENT_NAME = 'MAIN_INT'
    ) AS DATE_PREMIERE_ECHEANCE,
    (
        SELECT TO_CHAR(MAX(sc.schedule_due_date), 'YYYY-MM-DD')
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES sc
        WHERE sc.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
          AND sc.COMPONENT_NAME = 'MAIN_INT'
    ) AS DATE_DERNIERE_ECHEANCE,
    NVL(c.AMOUNT_FINANCED, 0) AS MONTANT_CAPITAL_ACCORDE,
    NVL(c.AMOUNT_FINANCED, 0) AS FINANCED_AMOUNT,
    (
        SELECT DECODE(
            MAX(sch.unit),
            'M', 'Mensuel',
            'Q', 'Trimestrielle',
            MAX(sch.unit)
        )
        FROM CFSFCUBS145.CLTBS_ACCOUNT_COMP_SCH sch
        WHERE sch.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    ) AS PERIODICITE,
    TO_CHAR(c.FIELD_NUMBER_2) AS CPT_DEPOT_GARANTIE,
    (
        SELECT NVL(SUM(DECODE(t.drcr_ind, 'C', t.lcy_amount, 0)), 0)
        FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES t
        WHERE t.RELATED_ACCOUNT = c.ACCOUNT_NUMBER
          AND t.AMOUNT_TAG = 'GUAR_DEPO_LIQD'
    ) AS MONTANT_DEPOT_GARANTIE_INIT,
    (
        SELECT NVL(
            SUM(DECODE(g.drcr_ind, 'C', g.lcy_amount, 0))
            - SUM(DECODE(g.drcr_ind, 'D', g.lcy_amount, 0)),
            0
        )
        FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES g
        WHERE g.AC_NO = TO_CHAR(c.FIELD_NUMBER_2)
    ) AS SOLDE_DEPOT_GARANTIE,
    (
        SELECT NVL(SUM(DECODE(t.drcr_ind, 'C', t.lcy_amount, 0)), 0)
        FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES t
        WHERE t.RELATED_ACCOUNT = c.ACCOUNT_NUMBER
          AND t.AMOUNT_TAG = 'PROC_FEES_LIQD'
    ) AS FRAIS_DOSSIER,
    (
        SELECT NVL(SUM(DECODE(t.drcr_ind, 'C', t.lcy_amount, 0)), 0)
        FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES t
        WHERE t.RELATED_ACCOUNT = c.ACCOUNT_NUMBER
          AND t.AMOUNT_TAG = 'INSUR_LIQD'
    ) AS FRAIS_ASSURANCE,
    (
        SELECT MAX(v.ude_value)
        FROM CFSFCUBS145.CLTBS_ACCOUNT_UDE_VALUES v
        WHERE v.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
          AND v.ude_id = 'INTEREST_RATE'
    ) AS TAUX_DE_CREDIT,
    c.FIELD_CHAR_5 AS TYPE_PRET_2,
    c.FIELD_CHAR_2 AS CODE_GESTION_PRET,
    c.FIELD_CHAR_2 AS MANAGER_CODE,
    (
        SELECT MAX(u.LOV_DESC)
        FROM CFSFCUBS145.UDTM_LOV u
        WHERE u.FIELD_NAME = 'GESTION_PRET'
          AND u.LOV = c.FIELD_CHAR_2
    ) AS CHARGE_D_AFFAIRE,
    (
        SELECT MAX(u.LOV_DESC)
        FROM CFSFCUBS145.UDTM_LOV u
        WHERE u.FIELD_NAME = 'GESTION_PRET'
          AND u.LOV = c.FIELD_CHAR_2
    ) AS MANAGER,
    NVL(ecof.ENCOURS_TOTAL, 0) AS ENCOURS_TOTAL,
    NVL(ecof.ENCOURS_TOTAL, 0) AS OUTSTANDING,
    NVL(sa.TOTAL_OUTSTANDING, 0) AS TOTAL_OUTSTANDING,
    NVL(ecof.ENCOURS_SAIN, 0) AS ENCOURS_SAIN,
    NVL(ecof.ENCOURS_SAIN, 0) AS HEALTHY_OUTSTANDING,
    NVL(ecof.ENCOURS_IMPAYE, 0) AS ENCOURS_IMPAYE,
    NVL(ecof.ENCOURS_IMPAYE, 0) AS UNPAID_AMOUNT,
    NVL(ecof.ENCOURS_IMPAYE, 0) AS OVERDUE_AMOUNT,
    NVL(ecof.POURCENTAGE_REMBOURSEMENT, 0) AS POURCENTAGE_REMBOURSEMENT,
    NVL(ecof.POURCENTAGE_REMBOURSEMENT, 0) AS REPAYMENT_PERCENT,
    c.USER_DEFINED_STATUS AS STATUT_DECLASSEMENT,
    c.USER_DEFINED_STATUS,
    DECODE(
        c.ACCOUNT_STATUS,
        'A', 'FINANCER',
        'L', 'SOLDER',
        'V', 'ANNULER',
        c.ACCOUNT_STATUS
    ) AS STATUT_PRET,
    CASE
        WHEN c.ACCOUNT_STATUS IN ('L', 'V') THEN 'solde'
        WHEN NVL(sa.TOTAL_OUTSTANDING, 0) <= 0 AND NVL(c.AMOUNT_FINANCED, 0) > 0 THEN 'solde'
        WHEN NVL(ecof.ENCOURS_IMPAYE, 0) > 0 THEN 'impaye'
        ELSE 'sain'
    END AS HEALTH_STATUS,
    CASE
        WHEN c.ACCOUNT_STATUS IN ('L', 'V') THEN 'paid'
        WHEN NVL(ecof.ENCOURS_IMPAYE, 0) > 0 THEN 'overdue'
        ELSE 'active'
    END AS STATUS,
    c.ACCOUNT_STATUS,
    NVL(
        (
            TRUNC(SYSDATE) - 1
        ) - (
            SELECT MIN(z.SCHEDULE_DUE_DATE)
            FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
            WHERE z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
              AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
              AND z.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
              AND (z.AMOUNT_DUE - z.AMOUNT_SETTLED) > 0
              AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
        ),
        0
    ) AS DUREE_IMPAYE_A_DATE,
    GREATEST(
        NVL(sa.PAR_DAYS, 0),
        NVL(
            (
                TRUNC(SYSDATE) - 1
            ) - (
                SELECT MIN(z.SCHEDULE_DUE_DATE)
                FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
                WHERE z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
                  AND z.COMPONENT_NAME IN ('PRINCIPAL', 'MAIN_INT', 'TAF_INT')
                  AND z.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
                  AND (z.AMOUNT_DUE - z.AMOUNT_SETTLED) > 0
                  AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
            ),
            0
        )
    ) AS PAR_DAYS,
    NVL((
        SELECT g.GL_DESC_E
        FROM CFSFCUBS145.CLTM_PRODUCT_RTH pr
        JOIN CFSFCUBS145.GLVW_GLMASTER_E g ON pr.ACCOUNT_HEAD = g.GL_CODE_E
        WHERE pr.PRODUCT_CODE = c.PRODUCT_CODE
          AND pr.ACCOUNTING_ROLE = 'LOAN_ACCOUNT'
          AND ROWNUM = 1
    ), NVL(c.PRODUCT_CODE, 'Crédit')) AS PRODUCT_TYPE,
    c.PRODUCT_CODE,
    b.BRANCH_NAME AS AGENCY,
    c.BRANCH_CODE,
    TO_CHAR(COALESCE(ed.TRN_DT, c.BOOK_DATE), 'YYYY-MM-DD') AS DISBURSEMENT_DATE,
    TO_CHAR(d.SCHEDULE_LINKAGE, 'YYYY-MM-DD') AS DISBURSEMENT_VALUE_DATE,
    TO_CHAR(c.MATURITY_DATE, 'YYYY-MM-DD') AS MATURITY_DATE,
    TO_CHAR(sa.NEXT_DUE_DATE, 'YYYY-MM-DD') AS NEXT_DUE_DATE,
    NVL(ecof.ENCOURS_TOTAL, 0) AS CAPITAL_DUE,
    NVL(sa.INTEREST_OUTSTANDING, 0) AS ACCRUED_INTEREST,
    NVL(sa.PENALTIES_OUTSTANDING, 0) AS PENALTIES,
    NVL(sa.FTC_OUTSTANDING, 0) AS FTC_DUE,
    NVL(sa.ACS_OUTSTANDING, 0) AS ACS_DUE,
    NVL(sa.OPENING_FEE_OUTSTANDING, 0) AS OPENING_FEE_DUE,
    NVL(sa.COFICARTE_FEE_OUTSTANDING, 0) AS COFICARTE_FEE_DUE,
    NVL(sa.DUE_AMOUNT, 0) AS DUE_AMOUNT,
    c.ACCOUNT_NUMBER AS LOAN_ACCOUNT,
    TO_CHAR(c.DR_PROD_AC) AS LINKED_ACCOUNT,
    NVL((
        SELECT bal.CURRENT_BALANCE
        FROM CFSFCUBS145.STVW_AC_BAL_SUM bal
        WHERE bal.CUST_AC_NO = TO_CHAR(c.DR_PROD_AC)
          AND ROWNUM = 1
    ), 0) AS ACCOUNT_BALANCE,
    GREATEST(0, NVL(c.AMOUNT_FINANCED, 0) - NVL(ecof.ENCOURS_TOTAL, 0)) AS TOTAL_REPAID
"""

_CREDIT_FROM_JOINS = """
FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
JOIN CFSFCUBS145.STTM_CUSTOMER sc ON sc.CUSTOMER_NO = c.CUSTOMER_ID
LEFT JOIN CFSFCUBS145.STTM_BRANCH b ON b.BRANCH_CODE = c.BRANCH_CODE
LEFT JOIN SCHEDULE_AGG sa ON sa.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
LEFT JOIN ENCOURS_COFINA ecof ON ecof.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
LEFT JOIN DEBLOCAGE d ON d.account_number = c.ACCOUNT_NUMBER
LEFT JOIN ECRITURE_DEBLOCAGE ed ON ed.RELATED_ACCOUNT = c.ACCOUNT_NUMBER
"""

_CREDIT_WITH_CLAUSE = "WITH " + _CREDIT_PRODUCTION_CTES + _CREDIT_SCHEDULE_CTE

CREDITS_LIST = (
    _CREDIT_WITH_CLAUSE
    + """
SELECT
"""
    + _CREDIT_SELECT_BODY
    + _CREDIT_FROM_JOINS
    + """
WHERE 1 = 1
  {active_filter}
  {client_filter}
  {branch_filter}
ORDER BY COALESCE(ed.TRN_DT, c.BOOK_DATE) DESC NULLS LAST
FETCH FIRST :limit ROWS ONLY
"""
)

CREDIT_BY_ID = (
    _CREDIT_WITH_CLAUSE
    + """
SELECT
"""
    + _CREDIT_SELECT_BODY
    + _CREDIT_FROM_JOINS
    + """
WHERE c.ACCOUNT_NUMBER = :loan_number
  AND c.ACCOUNT_STATUS <> 'V'
  {branch_filter}
FETCH FIRST 1 ROWS ONLY
"""
)

CREDIT_AMORTIZATION_SCHEDULE = """
WITH PENALITE AS (
    SELECT
        c.ACCOUNT_NUMBER AS NO_PRET,
        z.SCHEDULE_NO,
        SUM(NVL(z.AMOUNT_DUE, 0)) AS TOTAL_PENALITE,
        SUM(NVL(z.AMOUNT_SETTLED, 0)) AS TOTAL_PENALITE_PAYE,
        SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS TOTAL_PENALITE_RESTANT
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE
        c.ACCOUNT_STATUS NOT IN ('L', 'V')
        AND z.COMPONENT_NAME IN ('ODIN_PNTY', 'ODIN_PNTYT', 'ODPR_PNTY', 'ODPR_PNTYT')
    GROUP BY
        c.ACCOUNT_NUMBER,
        z.SCHEDULE_NO
),
BASE AS (
    SELECT
        ACCOUNT_NUMBER,
        SCHEDULE_DUE_DATE,
        SUM(NVL(AMOUNT_DUE, 0)) AS MONTANT_ECHEANCE,
        SUM(NVL(AMOUNT_SETTLED, 0)) AS MONTANT_ECHEANCE_PAYE,
        SUM(
            CASE
                WHEN SCHEDULE_DUE_DATE > TRUNC(SYSDATE) THEN 0
                ELSE NVL(AMOUNT_DUE, 0) - NVL(AMOUNT_SETTLED, 0)
            END
        ) AS MONTANT_ECHEANCE_IMPY
    FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES
    WHERE COMPONENT_NAME IN ('MAIN_INT', 'PRINCIPAL')
    GROUP BY
        ACCOUNT_NUMBER,
        SCHEDULE_DUE_DATE
),
BASE_NUM AS (
    SELECT
        e.*,
        ROW_NUMBER() OVER (
            PARTITION BY e.ACCOUNT_NUMBER
            ORDER BY e.SCHEDULE_DUE_DATE
        ) AS NUMERO_ECHEANCE
    FROM BASE e
),
FINAL AS (
    SELECT
        e.ACCOUNT_NUMBER,
        e.SCHEDULE_DUE_DATE,
        e.NUMERO_ECHEANCE,
        e.MONTANT_ECHEANCE,
        e.MONTANT_ECHEANCE_PAYE,
        e.MONTANT_ECHEANCE_IMPY,
        NVL(pen.TOTAL_PENALITE_RESTANT, 0) AS PENALITE,
        (NVL(e.MONTANT_ECHEANCE_IMPY, 0) + NVL(pen.TOTAL_PENALITE_RESTANT, 0)) AS EXIGIBLE,
        CASE
            WHEN (NVL(e.MONTANT_ECHEANCE_IMPY, 0) + NVL(pen.TOTAL_PENALITE_RESTANT, 0)) > 0
                THEN 'I'
            WHEN (NVL(e.MONTANT_ECHEANCE_IMPY, 0) + NVL(pen.TOTAL_PENALITE_RESTANT, 0)) = 0
                 AND e.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                THEN 'R'
            WHEN (NVL(e.MONTANT_ECHEANCE_IMPY, 0) + NVL(pen.TOTAL_PENALITE_RESTANT, 0)) = 0
                 AND e.SCHEDULE_DUE_DATE >= TRUNC(SYSDATE)
                THEN 'A'
            ELSE NULL
        END AS STATUS
    FROM BASE_NUM e
    LEFT JOIN PENALITE pen
        ON pen.NO_PRET = e.ACCOUNT_NUMBER
       AND pen.SCHEDULE_NO = e.NUMERO_ECHEANCE
)
SELECT *
FROM (
    SELECT *
    FROM FINAL
    WHERE ACCOUNT_NUMBER = :loan_number
    UNION ALL
    SELECT
        NULL AS ACCOUNT_NUMBER,
        NULL AS SCHEDULE_DUE_DATE,
        NULL AS NUMERO_ECHEANCE,
        SUM(MONTANT_ECHEANCE) AS MONTANT_ECHEANCE,
        SUM(MONTANT_ECHEANCE_PAYE) AS MONTANT_ECHEANCE_PAYE,
        SUM(MONTANT_ECHEANCE_IMPY) AS MONTANT_ECHEANCE_IMPY,
        SUM(PENALITE) AS PENALITE,
        SUM(EXIGIBLE) AS EXIGIBLE,
        NULL AS STATUS
    FROM FINAL
    WHERE ACCOUNT_NUMBER = :loan_number
)
ORDER BY NUMERO_ECHEANCE NULLS LAST
"""

DAT_DEPOSITS = """
SELECT
    ca.CUST_AC_NO AS ID,
    ac.DESCRIPTION AS LABEL,
    bal.CURRENT_BALANCE AS AMOUNT,
    TO_CHAR(ca.AC_OPEN_DATE + 365, 'YYYY-MM-DD') AS MATURITY_DATE,
    ca.CUST_NO AS CLIENT_ID,
    sc.FULL_NAME AS CLIENT_NAME,
    ca.BRANCH_CODE
FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS ac ON ac.ACCOUNT_CLASS = ca.ACCOUNT_CLASS
JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON bal.CUST_AC_NO = ca.CUST_AC_NO
JOIN CFSFCUBS145.STTM_CUSTOMER sc ON sc.CUSTOMER_NO = ca.CUST_NO
WHERE ac.ACCOUNT_CODE = '252'
  AND ca.RECORD_STAT = 'O'
  AND bal.CURRENT_BALANCE > 0
  {branch_filter}
ORDER BY bal.CURRENT_BALANCE DESC
FETCH FIRST :limit ROWS ONLY
"""

DASHBOARD_KPIS = """
SELECT
    (SELECT COUNT(*) FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
     WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V') {branch_filter_c}) AS ACTIVE_CREDITS,
    (SELECT NVL(SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)), 0)
     FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
     JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
     WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
       AND z.COMPONENT_NAME = 'PRINCIPAL'
       {branch_filter_c}) AS GLOBAL_OUTSTANDING,
    (SELECT COUNT(DISTINCT sc.CUSTOMER_NO)
     FROM CFSFCUBS145.STTM_CUSTOMER sc
     WHERE sc.RECORD_STAT = 'O'
       {branch_filter_sc}) AS ACTIVE_CLIENTS,
    (SELECT NVL(SUM(bal.CURRENT_BALANCE), 0)
     FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
     JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS ac ON ac.ACCOUNT_CLASS = ca.ACCOUNT_CLASS
     JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON bal.CUST_AC_NO = ca.CUST_AC_NO
     WHERE ac.ACCOUNT_CODE IN ('253', '252')
       AND ca.RECORD_STAT = 'O'
       {branch_filter_ca}) AS SAVINGS_COLLECTED,
    (SELECT COUNT(*)
     FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
     WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
       AND EXISTS (
           SELECT 1 FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
           WHERE z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
             AND NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
             AND z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
       )
       {branch_filter_c}) AS OVERDUE_CREDITS
FROM DUAL
"""

RISKS_PAR = """
SELECT
    CASE
        WHEN MAX_PAR_DAYS = 0 THEN 'par0'
        WHEN MAX_PAR_DAYS <= 30 THEN 'par30'
        WHEN MAX_PAR_DAYS <= 90 THEN 'par90'
        WHEN MAX_PAR_DAYS <= 180 THEN 'par180'
        ELSE 'par360'
    END AS PAR_CATEGORY,
    COUNT(DISTINCT CUSTOMER_ID) AS CLIENT_COUNT,
    NVL(SUM(OUTSTANDING), 0) AS TOTAL_EXPOSURE
FROM (
    SELECT
        c.CUSTOMER_ID,
        c.ACCOUNT_NUMBER,
        NVL(SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)), 0) AS OUTSTANDING,
        NVL(MAX(
            CASE
                WHEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) > 0
                     AND z.SCHEDULE_DUE_DATE < TRUNC(SYSDATE)
                THEN GREATEST(0, TRUNC(SYSDATE) - TRUNC(z.SCHEDULE_DUE_DATE))
                ELSE 0
            END
        ), 0) AS MAX_PAR_DAYS
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
      ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
      AND z.COMPONENT_NAME = 'PRINCIPAL'
      {branch_filter_c}
    GROUP BY c.CUSTOMER_ID, c.ACCOUNT_NUMBER
) t
GROUP BY CASE
    WHEN MAX_PAR_DAYS = 0 THEN 'par0'
    WHEN MAX_PAR_DAYS <= 30 THEN 'par30'
    WHEN MAX_PAR_DAYS <= 90 THEN 'par90'
    WHEN MAX_PAR_DAYS <= 180 THEN 'par180'
    ELSE 'par360'
END
ORDER BY MIN(CASE
    WHEN MAX_PAR_DAYS = 0 THEN 1
    WHEN MAX_PAR_DAYS <= 30 THEN 2
    WHEN MAX_PAR_DAYS <= 90 THEN 3
    WHEN MAX_PAR_DAYS <= 180 THEN 4
    ELSE 5
END)
"""

# Synthèse client : encours crédit par composante d'échéancier
CLIENT_CREDIT_ENCOURS_SUMMARY = """
SELECT
    NVL(SUM(CASE WHEN z.COMPONENT_NAME = 'PRINCIPAL'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS CAPITAL_DU,
    NVL(SUM(CASE WHEN z.COMPONENT_NAME = 'MAIN_INT'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS INTERET_DU,
    NVL(SUM(CASE
        WHEN z.COMPONENT_NAME IN ('FTC', 'MAIN_FTC')
             OR UPPER(z.COMPONENT_NAME) LIKE '%FTC%'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS FTC_DU,
    NVL(SUM(CASE
        WHEN z.COMPONENT_NAME IN ('ACS', 'MAIN_ACS', 'CHARGE_ACS')
             OR UPPER(z.COMPONENT_NAME) LIKE '%ACS%'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS CHARGE_ACS_DU,
    NVL(SUM(CASE
        WHEN z.COMPONENT_NAME IN ('PROC_FEE', 'MAIN_PROC', 'MAIN_FEE', 'FEE')
             OR UPPER(z.COMPONENT_NAME) LIKE '%FRAIS%'
             OR UPPER(z.COMPONENT_NAME) LIKE '%OUV%'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS FRAIS_OUVERTURE_DU,
    NVL(SUM(CASE
        WHEN UPPER(z.COMPONENT_NAME) LIKE '%COFI%'
             OR UPPER(z.COMPONENT_NAME) LIKE '%CARTE%'
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS FRAIS_COFICARTE_DU,
    NVL(SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)), 0) AS ENCOURS_GLOBAL,
    NVL(SUM(CASE WHEN z.SCHEDULE_DUE_DATE <= TRUNC(SYSDATE)
        THEN NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0) ELSE 0 END), 0) AS TOTAL_EXIGIBLE
FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
JOIN CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
  ON z.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
WHERE c.CUSTOMER_ID = :customer_no
  AND c.ACCOUNT_STATUS NOT IN ('L', 'V')
"""

# Dernier mouvement crédit (remboursement / liquidation) du client
LAST_CREDIT_MOVEMENT_BY_CUSTOMER = """
SELECT
    a.RELATED_ACCOUNT AS LOAN_NUMBER,
    DECODE(a.DRCR_IND, 'D', a.LCY_AMOUNT, 0) AS MOUVEMENT_DEBIT,
    DECODE(a.DRCR_IND, 'C', a.LCY_AMOUNT, 0) AS MOUVEMENT_CREDIT,
    TO_CHAR(a.VALUE_DT, 'YYYY-MM-DD') AS DATE_VALEUR,
    TO_CHAR(a.TRN_DT, 'YYYY-MM-DD') AS DATE_SAISIE,
    NVL(t.TRN_DESC, NVL(a.AMOUNT_TAG, 'Opération crédit')) AS LIBELLE_OPERATION
FROM CFSFCUBS145.ACVW_ALL_AC_ENTRIES a
JOIN CFSFCUBS145.CLTB_ACCOUNT_MASTER c
  ON c.ACCOUNT_NUMBER = a.RELATED_ACCOUNT
LEFT JOIN CFSFCUBS145.STTM_TRN_CODE t
  ON t.TRN_CODE = a.TRN_CODE
WHERE c.CUSTOMER_ID = :customer_no
  AND a.EVENT IN ('MLIQ', 'ALIQ')
ORDER BY a.VALUE_DT DESC, a.AC_ENTRY_SR_NO DESC
FETCH FIRST 1 ROWS ONLY
"""
