"""
Requêtes clients Vue 360 — tables DASH (REPORT_GROUPE).
Le schéma Flexcube CFSFCUBS145 n'est pas accessible ; on utilise CUSTOMERS + TMP_CLIENTS_FLEX.
"""

_LATEST_CUSTOMERS = """
c.MIGRATION_DATETIME = (SELECT MAX(MIGRATION_DATETIME) FROM CUSTOMERS)
"""

CUSTOMERS_LIST_DASH = f"""
SELECT
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS CUSTOMER_NO,
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS SC_CUSTOMER_NO,
    c.CUSTOMER_NAME1 AS FULL_NAME,
    c.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    NVL(f.EXT_REF_NO, c.CUST_AC_NO) AS MATRICULE,
    c.CUST_AC_NO AS ACCOUNT_NUMBER,
    c.CONTACT_NUMBER AS PHONE,
    NVL(c.LIB_SSECT, c.TYPE_COMPTE) AS SEGMENT,
    'active' AS STATUS,
    c.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CUSTOMERS c
LEFT JOIN TMP_CLIENTS_FLEX f
    ON UPPER(TRIM(f.CUSTOMER_NAME1)) = UPPER(TRIM(c.CUSTOMER_NAME1))
WHERE {_LATEST_CUSTOMERS}
  AND c.LOCAL_BRANCH IN ({{branch_placeholders}})
ORDER BY c.CUSTOMER_NAME1
FETCH FIRST :limit ROWS ONLY
"""

CUSTOMERS_SEARCH_NAME_DASH = f"""
SELECT
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS CUSTOMER_NO,
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS SC_CUSTOMER_NO,
    c.CUSTOMER_NAME1 AS FULL_NAME,
    c.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    NVL(f.EXT_REF_NO, c.CUST_AC_NO) AS MATRICULE,
    c.CUST_AC_NO AS ACCOUNT_NUMBER,
    c.CONTACT_NUMBER AS PHONE,
    NVL(c.LIB_SSECT, c.TYPE_COMPTE) AS SEGMENT,
    'active' AS STATUS,
    c.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CUSTOMERS c
LEFT JOIN TMP_CLIENTS_FLEX f
    ON UPPER(TRIM(f.CUSTOMER_NAME1)) = UPPER(TRIM(c.CUSTOMER_NAME1))
WHERE {_LATEST_CUSTOMERS}
  AND UPPER(c.CUSTOMER_NAME1) LIKE UPPER(:query)
  {{branch_filter}}
ORDER BY c.CUSTOMER_NAME1
FETCH FIRST :limit ROWS ONLY
"""

CUSTOMERS_SEARCH_ACCOUNT_DASH = f"""
SELECT
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS CUSTOMER_NO,
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS SC_CUSTOMER_NO,
    c.CUSTOMER_NAME1 AS FULL_NAME,
    c.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    NVL(f.EXT_REF_NO, c.CUST_AC_NO) AS MATRICULE,
    c.CUST_AC_NO AS ACCOUNT_NUMBER,
    c.CONTACT_NUMBER AS PHONE,
    NVL(c.LIB_SSECT, c.TYPE_COMPTE) AS SEGMENT,
    'active' AS STATUS,
    c.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CUSTOMERS c
LEFT JOIN TMP_CLIENTS_FLEX f
    ON UPPER(TRIM(f.CUSTOMER_NAME1)) = UPPER(TRIM(c.CUSTOMER_NAME1))
WHERE {_LATEST_CUSTOMERS}
  AND c.CUST_AC_NO LIKE :query
  {{branch_filter}}
ORDER BY c.CUSTOMER_NAME1
FETCH FIRST :limit ROWS ONLY
"""

CUSTOMERS_SEARCH_MATRICULE_DASH = """
SELECT
    f.CUSTOMER_NO,
    f.CUSTOMER_NO AS SC_CUSTOMER_NO,
    f.CUSTOMER_NAME1 AS FULL_NAME,
    f.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    f.EXT_REF_NO AS MATRICULE,
    f.EXT_REF_NO AS ACCOUNT_NUMBER,
    NULL AS PHONE,
    'Standard' AS SEGMENT,
    'active' AS STATUS,
    NULL AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM TMP_CLIENTS_FLEX f
WHERE UPPER(f.EXT_REF_NO) LIKE UPPER(:query)
   OR UPPER(f.KYC_REF_NO) LIKE UPPER(:query)
ORDER BY f.CUSTOMER_NAME1
FETCH FIRST :limit ROWS ONLY
"""

CUSTOMER_BY_ID_DASH = f"""
SELECT
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS CUSTOMER_NO,
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS SC_CUSTOMER_NO,
    c.CUSTOMER_NAME1 AS FULL_NAME,
    c.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    NVL(f.EXT_REF_NO, c.CUST_AC_NO) AS MATRICULE,
    c.CUST_AC_NO AS ACCOUNT_NUMBER,
    c.CONTACT_NUMBER AS PHONE,
    NVL(c.LIB_SSECT, c.TYPE_COMPTE) AS SEGMENT,
    'active' AS STATUS,
    c.LOCAL_BRANCH AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM CUSTOMERS c
LEFT JOIN TMP_CLIENTS_FLEX f
    ON f.CUSTOMER_NO = :customer_no
    OR UPPER(TRIM(f.CUSTOMER_NAME1)) = UPPER(TRIM(c.CUSTOMER_NAME1))
WHERE {_LATEST_CUSTOMERS}
  AND (
    f.CUSTOMER_NO = :customer_no
    OR c.CUST_AC_NO = :customer_no
    OR SUBSTR(c.CUST_AC_NO, 1, 6) = :customer_no
  )
  {{branch_filter}}
ORDER BY CASE
  WHEN f.CUSTOMER_NO = :customer_no THEN 0
  WHEN c.CUST_AC_NO = :customer_no THEN 1
  ELSE 2
END
FETCH FIRST 1 ROWS ONLY
"""

CUSTOMER_BY_ID_FLEX_ONLY = """
SELECT
    f.CUSTOMER_NO,
    f.CUSTOMER_NAME1 AS FULL_NAME,
    f.CUSTOMER_NAME1 AS FIRST_NAME,
    '' AS LAST_NAME,
    f.EXT_REF_NO AS MATRICULE,
    f.EXT_REF_NO AS ACCOUNT_NUMBER,
    NULL AS PHONE,
    'Standard' AS SEGMENT,
    'active' AS STATUS,
    NULL AS BRANCH_CODE,
    0 AS TOTAL_OUTSTANDING,
    0 AS SAVINGS_BALANCE,
    0 AS ACTIVE_CREDITS_COUNT,
    0 AS PAR_DAYS
FROM TMP_CLIENTS_FLEX f
WHERE f.CUSTOMER_NO = :customer_no
   OR f.EXT_REF_NO = :customer_no
FETCH FIRST 1 ROWS ONLY
"""

KYC_DASH_QUERY = f"""
SELECT
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS CUSTOMER_NO,
    NVL(f.EXT_REF_NO, c.CUST_AC_NO) AS NUMERO_NAFA,
    NULL AS CUSTOMER_PREFIX,
    NVL(c.LIB_SSECT, c.CUSTOMER_TYPE) AS CATEGORIE,
    c.CUSTOMER_TYPE,
    DECODE(c.CUSTOMER_TYPE, 'C', '2', 'I', '1', '1') AS TYPE_1,
    NULL AS IDENTIFICATIONREGISTER,
    NULL AS IDENTIFICATIONREGISTER_1,
    NULL AS COUNTRY,
    NULL AS LANGUAGE,
    NULL AS GENRE,
    NULL AS MIDDLE_NAME,
    c.CUSTOMER_NAME1 AS FIRST_NAME,
    c.CUSTOMER_NAME1 AS FULL_NAME,
    NULL AS DATE_OF_BIRTH,
    NULL AS PLACE_OF_BIRTH,
    NULL AS SEX,
    NULL AS P_NATIONAL_ID,
    NULL AS PASSPORT_NO,
    NULL AS PPT_ISS_DATE,
    NULL AS PPT_EXP_DATE,
    c.ADDRESS AS D_ADDRESS1,
    NULL AS E_MAIL,
    NULL AS MOB_ISD_NO,
    c.CONTACT_NUMBER AS TELEPHONE,
    c.CONTACT_NUMBER AS MOBILE_NUMBER,
    NULL AS MOTHER_MAIDEN_NAME,
    NVL(f.CUSTOMER_NO, c.CUST_AC_NO) AS SC_CUSTOMER_NO,
    c.LOCAL_BRANCH,
    c.LOCAL_BRANCH AS BRANCH_NAME,
    'OUVERT' AS RECORD_STAT,
    NULL AS DATE_CREATION,
    NULL AS CUST_CAT,
    NVL(c.LIB_SSECT, c.TYPE_COMPTE) AS CUST_CAT_DESC,
    'KYC_REF' AS UNIQUE_ID_NAME,
    f.KYC_REF_NO AS UNIQUE_ID_VALUE
FROM CUSTOMERS c
LEFT JOIN TMP_CLIENTS_FLEX f
    ON f.CUSTOMER_NO = :customer_no
    OR f.EXT_REF_NO = :customer_no
    OR UPPER(TRIM(f.CUSTOMER_NAME1)) = UPPER(TRIM(c.CUSTOMER_NAME1))
WHERE {_LATEST_CUSTOMERS}
  AND (
    f.CUSTOMER_NO = :customer_no
    OR c.CUST_AC_NO = :customer_no
    OR SUBSTR(c.CUST_AC_NO, 1, 6) = :customer_no
  )
  {{branch_filter}}
ORDER BY CASE
  WHEN c.CUST_AC_NO = :customer_no THEN 0
  WHEN f.CUSTOMER_NO = :customer_no THEN 1
  ELSE 2
END
FETCH FIRST 1 ROWS ONLY
"""

KYC_DASH_FLEX_ONLY = """
SELECT
    f.CUSTOMER_NO,
    f.EXT_REF_NO AS NUMERO_NAFA,
    NULL AS CUSTOMER_PREFIX,
    'Standard' AS CATEGORIE,
    'I' AS CUSTOMER_TYPE,
    '1' AS TYPE_1,
    NULL AS IDENTIFICATIONREGISTER,
    NULL AS IDENTIFICATIONREGISTER_1,
    NULL AS COUNTRY,
    NULL AS LANGUAGE,
    NULL AS GENRE,
    NULL AS MIDDLE_NAME,
    f.CUSTOMER_NAME1 AS FIRST_NAME,
    f.CUSTOMER_NAME1 AS FULL_NAME,
    NULL AS DATE_OF_BIRTH,
    NULL AS PLACE_OF_BIRTH,
    NULL AS SEX,
    NULL AS P_NATIONAL_ID,
    NULL AS PASSPORT_NO,
    NULL AS PPT_ISS_DATE,
    NULL AS PPT_EXP_DATE,
    NULL AS D_ADDRESS1,
    NULL AS E_MAIL,
    NULL AS MOB_ISD_NO,
    NULL AS TELEPHONE,
    NULL AS MOBILE_NUMBER,
    NULL AS MOTHER_MAIDEN_NAME,
    f.CUSTOMER_NO AS SC_CUSTOMER_NO,
    NULL AS LOCAL_BRANCH,
    NULL AS BRANCH_NAME,
    'OUVERT' AS RECORD_STAT,
    NULL AS DATE_CREATION,
    NULL AS CUST_CAT,
    'Standard' AS CUST_CAT_DESC,
    'KYC_REF' AS UNIQUE_ID_NAME,
    f.KYC_REF_NO AS UNIQUE_ID_VALUE
FROM TMP_CLIENTS_FLEX f
WHERE f.CUSTOMER_NO = :customer_no
   OR f.EXT_REF_NO = :customer_no
FETCH FIRST 1 ROWS ONLY
"""

CREDITS_DASH_LIST = """
SELECT
    p.ACCOUNT_NUMBER AS LOAN_NUMBER,
    NVL(f.CUSTOMER_NO, p.CR_PROD_AC) AS CLIENT_ID,
    p.CHARGE_AFFAIRE AS CLIENT_NAME,
    0 AS FINANCED_AMOUNT,
    0 AS OUTSTANDING,
    'active' AS STATUS,
    0 AS PAR_DAYS,
    p.CR_PROD_AC AS PRODUCT_TYPE,
    p.BRANCH_CODE,
    p.CHARGE_AFFAIRE AS MANAGER,
    TO_CHAR(p.DATE_MISE_EN_PLACE, 'YYYY-MM-DD') AS DISBURSEMENT_DATE,
    NULL AS MATURITY_DATE,
    NULL AS NEXT_DUE_DATE,
    0 AS CAPITAL_DUE,
    0 AS ACCRUED_INTEREST,
    0 AS PENALTIES,
    0 AS TOTAL_REPAID
FROM DASH_PRET p
LEFT JOIN TMP_CLIENTS_FLEX f ON f.EXT_REF_NO = p.CR_PROD_AC
WHERE p.MIGRATION_DATETIME = (
    SELECT MAX(MIGRATION_DATETIME) FROM DASH_PRET
)
  {client_filter}
  {branch_filter}
ORDER BY p.DATE_MISE_EN_PLACE DESC
FETCH FIRST :limit ROWS ONLY
"""
