"""
KPI agences / zones / dashboard — Oracle Flexcube + tables DASH.
"""

AGENCY_STATS_FLEXCUBE = """
SELECT
    b.BRANCH_CODE,
    b.BRANCH_NAME,
    NVL(clients.ACTIVE_CLIENTS, 0) AS ACTIVE_CLIENTS,
    NVL(credits.ACTIVE_CREDITS, 0) AS ACTIVE_CREDITS,
    NVL(credits.TOTAL_OUTSTANDING, 0) AS TOTAL_OUTSTANDING,
    NVL(savings.SAVINGS_COLLECTED, 0) AS SAVINGS_COLLECTED
FROM CFSFCUBS145.STTM_BRANCH b
LEFT JOIN (
    SELECT sc.LOCAL_BRANCH AS BRANCH_CODE,
           COUNT(DISTINCT sc.CUSTOMER_NO) AS ACTIVE_CLIENTS
    FROM CFSFCUBS145.STTM_CUSTOMER sc
    WHERE sc.RECORD_STAT = 'O'
    GROUP BY sc.LOCAL_BRANCH
) clients ON clients.BRANCH_CODE = b.BRANCH_CODE
LEFT JOIN (
    SELECT c.BRANCH_CODE,
           COUNT(DISTINCT c.ACCOUNT_NUMBER) AS ACTIVE_CREDITS,
           NVL(SUM(enc.OUTSTANDING), 0) AS TOTAL_OUTSTANDING
    FROM CFSFCUBS145.CLTB_ACCOUNT_MASTER c
    LEFT JOIN (
        SELECT z.ACCOUNT_NUMBER,
               SUM(NVL(z.AMOUNT_DUE, 0) - NVL(z.AMOUNT_SETTLED, 0)) AS OUTSTANDING
        FROM CFSFCUBS145.CLTB_ACCOUNT_SCHEDULES z
        WHERE z.COMPONENT_NAME = 'PRINCIPAL'
        GROUP BY z.ACCOUNT_NUMBER
    ) enc ON enc.ACCOUNT_NUMBER = c.ACCOUNT_NUMBER
    WHERE c.ACCOUNT_STATUS NOT IN ('L', 'V')
    GROUP BY c.BRANCH_CODE
) credits ON credits.BRANCH_CODE = b.BRANCH_CODE
LEFT JOIN (
    SELECT ca.BRANCH_CODE,
           NVL(SUM(bal.CURRENT_BALANCE), 0) AS SAVINGS_COLLECTED
    FROM CFSFCUBS145.STTM_CUST_ACCOUNT ca
    JOIN CFSFCUBS145.STTM_ACCOUNT_CLASS ac ON ac.ACCOUNT_CLASS = ca.ACCOUNT_CLASS
    JOIN CFSFCUBS145.STVW_AC_BAL_SUM bal ON bal.CUST_AC_NO = ca.CUST_AC_NO
    WHERE ac.ACCOUNT_CODE IN ('253', '252')
      AND ca.RECORD_STAT = 'O'
    GROUP BY ca.BRANCH_CODE
) savings ON savings.BRANCH_CODE = b.BRANCH_CODE
WHERE b.BRANCH_CODE IN ({branch_placeholders})
ORDER BY b.BRANCH_NAME
"""

DASH_PRODUCTION_BY_AGENCY = """
SELECT
    d.CODE_AGENCE,
    NVL(SUM(d.VOLUME_DEBLOQUE_M), 0) AS MONTHLY_PRODUCTION,
    NVL(SUM(d.VOLUME_DEBLOQUE_M_1), 0) AS MONTHLY_PRODUCTION_PREV
FROM DASH_PRODUCTION_VOLUME d
WHERE d.MIGRATION_DATETIME = (
    SELECT MAX(x.MIGRATION_DATETIME)
    FROM DASH_PRODUCTION_VOLUME x
    WHERE TO_CHAR(x.MIGRATION_DATE_MINUS1, 'MM/YYYY') = :month_year
)
  AND TRIM(TO_CHAR(d.CODE_AGENCE)) IN ({branch_placeholders})
GROUP BY d.CODE_AGENCE
"""

DASH_ENCOURS_12M_BY_AGENCY = """
SELECT
    TRIM(TO_CHAR(d.CODE_AGENCE)) AS CODE_AGENCE,
    TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') AS MONTH_YEAR,
    NVL(SUM(d.PTF_M), 0) AS PTF_M
FROM DASH_EVOLUTION_ENCOURS d
WHERE d.MIGRATION_DATETIME = (
    SELECT MAX(x.MIGRATION_DATETIME)
    FROM DASH_EVOLUTION_ENCOURS x
    WHERE TO_CHAR(x.MIGRATION_DATE_MINUS1, 'MM/YYYY') = TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
)
  AND TRIM(TO_CHAR(d.CODE_AGENCE)) IN ({branch_placeholders})
  AND d.MIGRATION_DATE_MINUS1 >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
GROUP BY TRIM(TO_CHAR(d.CODE_AGENCE)), TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
ORDER BY CODE_AGENCE, MIN(d.MIGRATION_DATE_MINUS1)
"""

DASH_ENCOURS_12M = """
SELECT
    TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') AS MONTH_YEAR,
    NVL(SUM(d.PTF_M), 0) AS PTF_M
FROM DASH_EVOLUTION_ENCOURS d
WHERE d.MIGRATION_DATETIME = (
    SELECT MAX(x.MIGRATION_DATETIME)
    FROM DASH_EVOLUTION_ENCOURS x
    WHERE TO_CHAR(x.MIGRATION_DATE_MINUS1, 'MM/YYYY') = TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
)
  AND TRIM(TO_CHAR(d.CODE_AGENCE)) IN ({branch_placeholders})
  AND d.MIGRATION_DATE_MINUS1 >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
GROUP BY TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
ORDER BY MIN(d.MIGRATION_DATE_MINUS1)
"""

DASH_PAR_12M = """
SELECT
    TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY') AS MONTH_YEAR,
    CASE
        WHEN NVL(SUM(d.ENCOURS_TOTAL), 0) > 0
        THEN ROUND(NVL(SUM(d.ENCOURS_PAR_30), 0) / SUM(d.ENCOURS_TOTAL) * 100, 2)
        ELSE 0
    END AS PAR30
FROM DASH_PAR_GLOBAL d
WHERE d.MIGRATION_DATETIME = (
    SELECT MAX(x.MIGRATION_DATETIME)
    FROM DASH_PAR_GLOBAL x
    WHERE TO_CHAR(x.MIGRATION_DATE_MINUS1, 'MM/YYYY') = TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
)
  AND d.MIGRATION_DATE_MINUS1 >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
  {branch_filter}
GROUP BY TO_CHAR(d.MIGRATION_DATE_MINUS1, 'MM/YYYY')
ORDER BY MIN(d.MIGRATION_DATE_MINUS1)
"""

DASH_PAR_12M_BY_BRANCH = DASH_PAR_12M.replace(
    "{branch_filter}",
    "AND EXISTS (SELECT 1 FROM CFSFCUBS145.STTM_BRANCH br "
    "WHERE br.BRANCH_NAME = d.BRANCH_NAME "
    "AND br.BRANCH_CODE IN ({branch_placeholders}))",
)

DASH_NETWORK_PRODUCTION = """
SELECT
    NVL(SUM(d.VOLUME_DEBLOQUE_M), 0) AS MONTHLY_PRODUCTION,
    NVL(SUM(d.VOLUME_DEBLOQUE_M_1), 0) AS MONTHLY_PRODUCTION_PREV
FROM DASH_PRODUCTION_VOLUME d
WHERE d.MIGRATION_DATETIME = (
    SELECT MAX(x.MIGRATION_DATETIME)
    FROM DASH_PRODUCTION_VOLUME x
    WHERE TO_CHAR(x.MIGRATION_DATE_MINUS1, 'MM/YYYY') = :month_year
)
  {branch_filter}
"""

DASH_NETWORK_PRODUCTION_BY_BRANCH = DASH_NETWORK_PRODUCTION.replace(
    "{branch_filter}",
    "AND TRIM(TO_CHAR(d.CODE_AGENCE)) IN ({branch_placeholders})",
)
