# Tables DASH Wave (Cofina) — snapshot MAX(MIGRATION_DATETIME) comme Orange Money / Volume DAT.


def sql_dash_envoi_wave(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_ENVOIE_WAV_M_1,
    VOLUME_ENVOIE_WAV_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_ENVOIE_WAVE
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_ENVOIE_WAVE d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""


def sql_dash_paiement_wave(inner_where: str) -> str:
    return f"""
SELECT
    CODE_AGENCE,
    LIBELLE_AGENCE,
    VOLUME_PAIEMENT_WAV_M_1,
    VOLUME_PAIEMENT_WAV_M,
    VARIATION_VOLUME,
    "VARIATION%",
    MIGRATION_DATE,
    MIGRATION_DATETIME,
    MIGRATION_DATE_MINUS1
FROM DASH_PAIEMENT_WAVE
WHERE MIGRATION_DATETIME = (
    SELECT MAX(d.MIGRATION_DATETIME)
    FROM DASH_PAIEMENT_WAVE d
    WHERE {inner_where}
)
ORDER BY CODE_AGENCE, LIBELLE_AGENCE
"""
